//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdherenciaDesviacionCongelado
    {
        public int Id { get; set; }
        public int Anio { get; set; }
        public int Semana { get; set; }
        public System.DateTime FecModif { get; set; }
        public string Linea { get; set; }
        public string WO { get; set; }
        public string Formato { get; set; }
        public string IdPaleta { get; set; }
        public string ItemMD { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FecIniPlan { get; set; }
        public Nullable<System.DateTime> FecFinPlan { get; set; }
        public Nullable<System.DateTime> FecIniReal { get; set; }
        public Nullable<System.DateTime> FecFinReal { get; set; }
        public double DesvIni { get; set; }
        public double DesvFin { get; set; }
        public double HorasPlan { get; set; }
        public double DesviacionObjetivo { get; set; }
        public string IdMotivo { get; set; }
        public string Comentario { get; set; }
    
        public virtual AdherenciaMotivos AdherenciaMotivos { get; set; }
    }
}
