//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdherenciaDesviacionSecuencia
    {
        public int Id { get; set; }
        public string TipoComparacion { get; set; }
        public int Anio { get; set; }
        public int Semana { get; set; }
        public string Linea { get; set; }
        public System.DateTime FecModif { get; set; }
        public string SecuenciaPlanificada { get; set; }
        public string SecuenciaReal { get; set; }
        public string PrimerProductoDesviado { get; set; }
        public string IdMotivo { get; set; }
        public string Comentario { get; set; }
    
        public virtual AdherenciaMotivos AdherenciaMotivos { get; set; }
    }
}
