//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdherenciaMotivos
    {
        public AdherenciaMotivos()
        {
            this.AdherenciaDesviacionCongelado = new HashSet<AdherenciaDesviacionCongelado>();
            this.AdherenciaDesviacionSecuencia = new HashSet<AdherenciaDesviacionSecuencia>();
            this.AdherenciaDesviacionVolumen = new HashSet<AdherenciaDesviacionVolumen>();
        }
    
        public string Motivo { get; set; }
        public string Origen { get; set; }
        public string IdMotivo { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<AdherenciaDesviacionCongelado> AdherenciaDesviacionCongelado { get; set; }
        public virtual ICollection<AdherenciaDesviacionSecuencia> AdherenciaDesviacionSecuencia { get; set; }
        public virtual ICollection<AdherenciaDesviacionVolumen> AdherenciaDesviacionVolumen { get; set; }
    }
}
