//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalisisSPI
    {
        public int ANYO { get; set; }
        public short SEMANA { get; set; }
        public string TIPO_ANALISIS { get; set; }
        public string COMENTARIOS { get; set; }
        public string LINEA { get; set; }
    }
}
