//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Celda_FAB
    {
        public int CeldaPK { get; set; }
        public string ID { get; set; }
        public Nullable<int> AreaPK { get; set; }
        public bool IsInPlant { get; set; }
        public string Name { get; set; }
        public string Level { get; set; }
        public int ClassPK { get; set; }
        public string ClassID { get; set; }
        public string ModuleName { get; set; }
        public string C_External_IDSloc { get; set; }
        public string equipPropL9 { get; set; }
        public string TipoUbicacion { get; set; }
        public Nullable<int> Posicion { get; set; }
    }
}
