//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CocPlanning
    {
        public long Index { get; set; }
        public string CodArticle { get; set; }
        public string Article { get; set; }
        public string ExistenciasTCP { get; set; }
        public string Necesidad { get; set; }
        public string Cocciones { get; set; }
    }
}
