//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionMaquinasCompartidas
    {
        public int Id { get; set; }
        public string Linea { get; set; }
        public string Maquina { get; set; }
        public bool Activa { get; set; }
        public string Agrupacion { get; set; }
        public Nullable<int> Ordenacion { get; set; }
    }
}
