//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionEmpaquetadoras
    {
        public long Id { get; set; }
        public string Linea { get; set; }
        public string Producto { get; set; }
        public string Empaquetadora { get; set; }
        public bool Suma { get; set; }
    }
}
