//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumosMateriales_FAB
    {
        public string IdMaterial { get; set; }
        public Nullable<double> Cantidad_Estimada { get; set; }
        public string location_id { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public string UOM { get; set; }
        public string name { get; set; }
        public string Descripcion_Material { get; set; }
        public string IdOrden { get; set; }
        public int tipo { get; set; }
        public string loteMES { get; set; }
        public System.DateTime RowUpdated { get; set; }
    }
}
