//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeslizanteGeneral
    {
        public int Id { get; set; }
        public int Semanas { get; set; }
        public int IdDia { get; set; }
        public string Hora { get; set; }
    }
}
