//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeslizanteLineas
    {
        public int id { get; set; }
        public Nullable<int> numLinea { get; set; }
        public string descripcion { get; set; }
        public int orden { get; set; }
        public string codigoJDE { get; set; }
        public string aplicacion { get; set; }
        public string nombreLinea { get; set; }
    }
}
