//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeslizanteEnvasado
    {
        public int Id { get; set; }
        public string Linea { get; set; }
        public string Formato { get; set; }
        public string Item { get; set; }
        public string Paleta { get; set; }
        public string Descripcion { get; set; }
        public int Anio { get; set; }
        public int Semana { get; set; }
        public int Cantidad { get; set; }
    }
}
