//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuotankHistorico
    {
        public int IdDuotankHistorico { get; set; }
        public Nullable<int> IdZona { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Matricula { get; set; }
        public string Operacion { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
    }
}
