//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        public string Id { get; set; }
        public string Nombre { get; set; }
        public string IdBD { get; set; }
        public string EquipoSuperior { get; set; }
        public Nullable<int> IdEquipoSuperior { get; set; }
        public string Nivel { get; set; }
        public int IdNivel { get; set; }
        public string Clase { get; set; }
        public Nullable<int> IdClase { get; set; }
        public short Estado { get; set; }
        public string Descripcion { get; set; }
        public int PkEquipo { get; set; }
        public string Posicion { get; set; }
        public string RechazoManual { get; set; }
    }
}
