//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquiposConstructivosEnvasado
    {
        public EquiposConstructivosEnvasado()
        {
            this.DescripcionAverias = new HashSet<DescripcionAverias>();
            this.MantenimientoIntervenciones = new HashSet<MantenimientoIntervenciones>();
        }
    
        public string CodigoEquipo { get; set; }
        public string CodigoMaquina { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaUltimaActualizacion { get; set; }
        public int NumeroJustificaciones { get; set; }
    
        public virtual ICollection<DescripcionAverias> DescripcionAverias { get; set; }
        public virtual ICollection<MantenimientoIntervenciones> MantenimientoIntervenciones { get; set; }
    }
}
