//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo_FAB
    {
        public int EquipoPK { get; set; }
        public string ID { get; set; }
        public Nullable<int> CeldaPK { get; set; }
        public bool IsInPlant { get; set; }
        public string Name { get; set; }
        public string Level { get; set; }
        public int ClassPK { get; set; }
        public string ClassID { get; set; }
        public string ModuleName { get; set; }
        public string ID_ORDEN { get; set; }
        public string Descripcion { get; set; }
        public string Tipo_Ubicacion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Posicion { get; set; }
        public Nullable<int> Capacidad_Maxima { get; set; }
    }
}
