//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspecificacionMateriales_FAB
    {
        public int Cod_POM_Material { get; set; }
        public string NombreEM { get; set; }
        public string TipoEM { get; set; }
        public string Id_Material { get; set; }
        public string Descripcion_Material { get; set; }
        public int Cod_Orden { get; set; }
        public string Id_ORDEN { get; set; }
        public string Id_Localizacion { get; set; }
        public Nullable<double> Cantidad_Actual { get; set; }
        public Nullable<double> Cantidad_Estimada { get; set; }
        public string location_id { get; set; }
        public string Unidad_Medida { get; set; }
        public string Id_Material_Actual { get; set; }
        public string ActualERPLotID { get; set; }
        public string Id_Lote { get; set; }
        public string Alias { get; set; }
        public int UniqueNumber { get; set; }
        public Nullable<System.DateTime> RowUpdated { get; set; }
        public System.DateTime RowUpdatedUTC { get; set; }
        public string Equipo_Origen { get; set; }
        public string Id_POM_ENTRY { get; set; }
        public int Cod_POM_ENTRY { get; set; }
    }
}
