//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadosKOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstadosKOP()
        {
            this.KOPs = new HashSet<KOPs>();
            this.KOPsMultivalor = new HashSet<KOPsMultivalor>();
            this.MaestroKOPs = new HashSet<MaestroKOPs>();
            this.MaestroKOPs_Mostos_Ubicacion = new HashSet<MaestroKOPs_Mostos_Ubicacion>();
            this.MaestroValoresKOPsMultivalor = new HashSet<MaestroValoresKOPsMultivalor>();
            this.MaestroKOPsMultivalor = new HashSet<MaestroKOPsMultivalor>();
        }
    
        public int IdEstadoKOP { get; set; }
        public string DescEstadoKOP { get; set; }
        public string ColorEstadoKOP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOPs> KOPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOPsMultivalor> KOPsMultivalor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaestroKOPs> MaestroKOPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaestroKOPs_Mostos_Ubicacion> MaestroKOPs_Mostos_Ubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaestroValoresKOPsMultivalor> MaestroValoresKOPsMultivalor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaestroKOPsMultivalor> MaestroKOPsMultivalor { get; set; }
    }
}
