//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FillersByTCP
    {
        public Nullable<long> PK { get; set; }
        public Nullable<int> PkEquipo { get; set; }
        public long IdObj { get; set; }
        public string IdLinea { get; set; }
        public string IdTCP { get; set; }
        public string Nombre { get; set; }
        public string Clase { get; set; }
    }
}
