//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONES
    {
        public int ID_FUNCION { get; set; }
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> ID_AREA { get; set; }
        public Nullable<int> IdEstructura { get; set; }
    
        public virtual AREAS_GESTION AREAS_GESTION { get; set; }
        public virtual EstructuraPermisos EstructuraPermisos { get; set; }
    }
}
