//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraficaProduccionTeoricaVSReal
    {
        public long Id { get; set; }
        public string Linea { get; set; }
        public int Turno { get; set; }
        public string IdProducto { get; set; }
        public int VelocidadNominal { get; set; }
        public int VelocidadNominalMaqLimitante { get; set; }
        public decimal RendimientoObjetivo { get; set; }
        public int ProduccionVelocidadNominal { get; set; }
        public int ProduccionVelocidadNominalRndObjetivo { get; set; }
        public int ProduccionVelocidadNominalMaqLimitante { get; set; }
        public Nullable<int> ProduccionReal { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
