//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JustificacionParosMotivos
    {
        public int IdMotivo { get; set; }
        public string Descripcion { get; set; }
        public short IdArbolMotivo { get; set; }
        public string CodigoMotivo { get; set; }
        public bool MaquinaObligatoria { get; set; }
        public bool Activo { get; set; }
    }
}
