//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOPs_FAB_Historian
    {
        public int Cod_KOP { get; set; }
        public string ID_KOP { get; set; }
        public string Des_KOP { get; set; }
        public int Cod_Orden { get; set; }
        public string ID_Orden { get; set; }
        public string ID_Procedimiento { get; set; }
        public int Cod_Procedimiento { get; set; }
        public string Tipo_KOP { get; set; }
        public int Valor_Actual { get; set; }
        public int Valor_Minimo { get; set; }
        public int Valor_Maximo { get; set; }
        public int Obligatorio { get; set; }
        public string UOM_KOP { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public System.DateTime FechaUTC { get; set; }
        public string TipoKOP { get; set; }
        public Nullable<int> Sequence_Procedimiento { get; set; }
        public int PkActVal { get; set; }
        public int Sequence_KOP { get; set; }
    }
}
