//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOPs
    {
        public int IdKOP { get; set; }
        public string ValorMin { get; set; }
        public string Valor { get; set; }
        public string ValorMax { get; set; }
        public Nullable<System.DateTime> FechaActualizado { get; set; }
        public int IdEstadoKOP { get; set; }
        public int IdWO { get; set; }
        public int IdMaestroKOP { get; set; }
    
        public virtual EstadosKOP EstadosKOP { get; set; }
        public virtual MaestroKOPs MaestroKOPs { get; set; }
        public virtual WOs WOs { get; set; }
    }
}
