//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineasDobleSalidaConfiguracion
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string ZonaLlenadoraPrimeraLinea { get; set; }
        public string ZonaLlenadoraSegundaLinea { get; set; }
        public string ZonaPaleteraPrimeralinea { get; set; }
        public string ZonaPaleteraSegundaLinea { get; set; }
        public string VariableRTDSPrimeraLinea { get; set; }
        public string VariableRTDSSegundaLinea { get; set; }
    }
}
