//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoteUbicacion_FAB
    {
        public int LocPK { get; set; }
        public string LOCID { get; set; }
        public string LocPath { get; set; }
        public Nullable<int> ParentLocPK { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> InitQuantity { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string UomID { get; set; }
        public string PoliticaVaciado { get; set; }
        public string LoteMes { get; set; }
    }
}
