//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoteUbicacionMaterial_FAB
    {
        public int LocPK { get; set; }
        public string LOCID { get; set; }
        public string LocPath { get; set; }
        public Nullable<int> ParentLocPK { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public System.DateTime LastUpdateUTC { get; set; }
        public string Descripcion { get; set; }
        public int LotPK { get; set; }
        public Nullable<decimal> InitQuantity { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string UomID { get; set; }
        public string DefID { get; set; }
        public string Descript { get; set; }
        public int DefPK { get; set; }
        public string ClassDescript { get; set; }
        public string serialNumber { get; set; }
        public string PoliticaVaciado { get; set; }
        public string LoteMes { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Parent { get; set; }
    }
}
