//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroKOPs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaestroKOPs()
        {
            this.KOPs = new HashSet<KOPs>();
            this.VariablesFormulaKOP = new HashSet<VariablesFormulaKOP>();
            this.VariablesFormulaKOP1 = new HashSet<VariablesFormulaKOP>();
            this.MaestroKOPs_Mostos_Ubicacion = new HashSet<MaestroKOPs_Mostos_Ubicacion>();
        }
    
        public int IdMaestroKOP { get; set; }
        public string CodKOP { get; set; }
        public string DescKOP { get; set; }
        public string MensajeKOP { get; set; }
        public string Unidad { get; set; }
        public string TipodatoMaestroKOP { get; set; }
        public int IdTipoKOP { get; set; }
        public int IdTipoSubproceso { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> FechaActualizado { get; set; }
        public string ValorMin { get; set; }
        public string ValorDefecto { get; set; }
        public string ValorMax { get; set; }
        public bool Editable { get; set; }
        public int IdEstadoKOP { get; set; }
        public int IdZona { get; set; }
    
        public virtual EstadosKOP EstadosKOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOPs> KOPs { get; set; }
        public virtual TiposSubprocesos TiposSubprocesos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VariablesFormulaKOP> VariablesFormulaKOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VariablesFormulaKOP> VariablesFormulaKOP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaestroKOPs_Mostos_Ubicacion> MaestroKOPs_Mostos_Ubicacion { get; set; }
    }
}
