//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroKOPsMultivalor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaestroKOPsMultivalor()
        {
            this.KOPsMultivalor = new HashSet<KOPsMultivalor>();
            this.MaestroValoresKOPsMultivalor = new HashSet<MaestroValoresKOPsMultivalor>();
        }
    
        public int IdMaestroKOPMultivalor { get; set; }
        public string DescKOP { get; set; }
        public string MensajeKOP { get; set; }
        public string Unidad { get; set; }
        public string TipodatoMaestroKOP { get; set; }
        public int IdTipoSubproceso { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> FechaActualizado { get; set; }
        public int IdTipoKOPMultivalor { get; set; }
        public int IdEstadoKOP { get; set; }
        public int IdZona { get; set; }
        public string CodKOP { get; set; }
        public int NKOPMultivalor { get; set; }
    
        public virtual EstadosKOP EstadosKOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOPsMultivalor> KOPsMultivalor { get; set; }
        public virtual TiposKOPMultivalor TiposKOPMultivalor { get; set; }
        public virtual TiposSubprocesos TiposSubprocesos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaestroValoresKOPsMultivalor> MaestroValoresKOPsMultivalor { get; set; }
    }
}
