//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroValoresKOPsMultivalor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaestroValoresKOPsMultivalor()
        {
            this.ValoresKOPsMultivalor = new HashSet<ValoresKOPsMultivalor>();
        }
    
        public int IdMaestroValorKOPMultivalor { get; set; }
        public string DescValorKOP { get; set; }
        public string ValorMin { get; set; }
        public string ValorDefecto { get; set; }
        public string ValorMax { get; set; }
        public int IdMaestroKOPMultivalor { get; set; }
        public Nullable<System.DateTime> FechaActualizado { get; set; }
        public int Posicion { get; set; }
        public bool Activo { get; set; }
        public int IdEstadoValorKOP { get; set; }
    
        public virtual EstadosKOP EstadosKOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValoresKOPsMultivalor> ValoresKOPsMultivalor { get; set; }
        public virtual MaestroKOPsMultivalor MaestroKOPsMultivalor { get; set; }
    }
}
