//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroAreasFabricacion
    {
        public MaestroAreasFabricacion()
        {
            this.MaestroZonasFabricacion = new HashSet<MaestroZonasFabricacion>();
            this.MantenimientoIntervenciones = new HashSet<MantenimientoIntervenciones>();
        }
    
        public int IdAreaFabricacion { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Descripcion2 { get; set; }
        public string Descripcion3 { get; set; }
    
        public virtual ICollection<MaestroZonasFabricacion> MaestroZonasFabricacion { get; set; }
        public virtual ICollection<MantenimientoIntervenciones> MantenimientoIntervenciones { get; set; }
    }
}
