//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroZonasFabricacion
    {
        public MaestroZonasFabricacion()
        {
            this.MaestroEquiposFabricacion = new HashSet<MaestroEquiposFabricacion>();
            this.MantenimientoIntervenciones = new HashSet<MantenimientoIntervenciones>();
        }
    
        public int IdZonaFabricacion { get; set; }
        public int IdAreaFabricacion { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Descripcion2 { get; set; }
        public string Descripcion3 { get; set; }
    
        public virtual MaestroAreasFabricacion MaestroAreasFabricacion { get; set; }
        public virtual ICollection<MaestroEquiposFabricacion> MaestroEquiposFabricacion { get; set; }
        public virtual ICollection<MantenimientoIntervenciones> MantenimientoIntervenciones { get; set; }
    }
}
