//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailGroup
    {
        public MailGroup()
        {
            this.MailNotification = new HashSet<MailNotification>();
            this.MailPartesCalidadNoValidos = new HashSet<MailPartesCalidadNoValidos>();
            this.MailMalaGestionWO = new HashSet<MailMalaGestionWO>();
            this.MailPartesCalidadPendientes = new HashSet<MailPartesCalidadPendientes>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserAddress { get; set; }
    
        public virtual ICollection<MailNotification> MailNotification { get; set; }
        public virtual ICollection<MailPartesCalidadNoValidos> MailPartesCalidadNoValidos { get; set; }
        public virtual ICollection<MailMalaGestionWO> MailMalaGestionWO { get; set; }
        public virtual ICollection<MailPartesCalidadPendientes> MailPartesCalidadPendientes { get; set; }
    }
}
