//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailMalaGestionWO
    {
        public MailMalaGestionWO()
        {
            this.MailGroup = new HashSet<MailGroup>();
        }
    
        public int Id { get; set; }
        public string Asunto { get; set; }
        public string CuerpoMensaje { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
    
        public virtual ICollection<MailGroup> MailGroup { get; set; }
    }
}
