//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailNotification
    {
        public MailNotification()
        {
            this.MailGroup = new HashSet<MailGroup>();
        }
    
        public int Id { get; set; }
        public string UserAddress { get; set; }
        public int StoppageTime { get; set; }
        public Nullable<System.DateTime> SendedOn { get; set; }
        public string Subject { get; set; }
        public string BodyMessage { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<MailGroup> MailGroup { get; set; }
    }
}
