//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantenimientoDatosValidacionArranqueOT
    {
        public int Id { get; set; }
        public int OT { get; set; }
        public string ResponsableProduccion { get; set; }
        public string ResponsableMantenimiento { get; set; }
        public System.DateTime FechaValidacion { get; set; }
    }
}
