//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantenimientoEstados
    {
        public MantenimientoEstados()
        {
            this.MantenimientoCambiosEstados = new HashSet<MantenimientoCambiosEstados>();
        }
    
        public int IdEstado { get; set; }
        public string CodigoEstado { get; set; }
        public string DescripcionEstado { get; set; }
        public string NombreEstado { get; set; }
        public string GrupoMTTR { get; set; }
        public string DescGrupoMTTR { get; set; }
        public Nullable<int> NTiempoMTTR { get; set; }
        public bool esEstadoJDE { get; set; }
        public int Orden { get; set; }
    
        public virtual ICollection<MantenimientoCambiosEstados> MantenimientoCambiosEstados { get; set; }
    }
}
