//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantenimientoEquivalenciaCausas
    {
        public int IdTipoAveriaOT { get; set; }
        public int IdCausaParo { get; set; }
    
        public virtual TipoAveria TipoAveria { get; set; }
    }
}
