//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantenimientoIntervenciones
    {
        public int IdMantenimientoIntervenciones { get; set; }
        public int OT { get; set; }
        public string Estado { get; set; }
        public string Linea { get; set; }
        public string Maquina { get; set; }
        public string EquipoConstructivo { get; set; }
        public Nullable<int> IdAreaFabricacion { get; set; }
        public Nullable<int> IdZonaFabricacion { get; set; }
        public Nullable<int> IdEquipoFabricacion { get; set; }
        public Nullable<int> IdGrupoConstructivoFabricacion { get; set; }
        public Nullable<int> IdRepuestoFabricacion { get; set; }
        public int IdTipoAveria { get; set; }
        public string DescripcionAveria { get; set; }
        public string DescripcionProblema { get; set; }
        public string ComentarioCierre { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> FechaActualizado { get; set; }
        public bool CerradoEnJDE { get; set; }
        public bool EsEnvasado { get; set; }
    
        public virtual EquiposConstructivosEnvasado EquiposConstructivosEnvasado { get; set; }
        public virtual MaestroAreasFabricacion MaestroAreasFabricacion { get; set; }
        public virtual MaestroEquiposFabricacion MaestroEquiposFabricacion { get; set; }
        public virtual MaestroGruposConstructivosFabricacion MaestroGruposConstructivosFabricacion { get; set; }
        public virtual MaestroRepuestosFabricacion MaestroRepuestosFabricacion { get; set; }
        public virtual MaestroZonasFabricacion MaestroZonasFabricacion { get; set; }
        public virtual TipoAveria TipoAveria { get; set; }
    }
}
