//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantenimientoCambiosEstados
    {
        public int Id { get; set; }
        public int OT { get; set; }
        public int IdMantenimientoEstados { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string UsuarioJDE { get; set; }
        public System.DateTime FechaActualizado { get; set; }
    
        public virtual MantenimientoEstados MantenimientoEstados { get; set; }
    }
}
