//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maquinas
    {
        public int PkEquipo { get; set; }
        public string Id { get; set; }
        public string Nombre { get; set; }
        public string IdBD { get; set; }
        public string Linea { get; set; }
        public Nullable<int> IdLinea { get; set; }
        public string Nivel { get; set; }
        public int IdNivel { get; set; }
        public string Clase { get; set; }
        public Nullable<int> IdClase { get; set; }
        public string Descripcion { get; set; }
        public string Zona { get; set; }
        public string Orden { get; set; }
        public Nullable<System.DateTime> FecHorActOrden { get; set; }
        public int Estado { get; set; }
        public Nullable<int> Posicion { get; set; }
        public string RechazoManual { get; set; }
        public int MENOR_LLENADORA { get; set; }
    }
}
