//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaquinasLineas
    {
        public Nullable<short> NumLinea { get; set; }
        public string Id { get; set; }
        public string Nombre { get; set; }
        public string Clase { get; set; }
        public Nullable<int> IdClase { get; set; }
        public string Descripcion { get; set; }
        public int PkEquipo { get; set; }
    }
}
