//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MermasContadores
    {
        public int IdMermaContador { get; set; }
        public int IdMermaMaquinaContador { get; set; }
        public int IdMermaRegistro { get; set; }
        public decimal Valor { get; set; }
        public string Unidad { get; set; }
        public string Justificacion { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public System.DateTime FechaActualizado { get; set; }
    
        public virtual MermasRegistros MermasRegistros { get; set; }
        public virtual MermasMaquinasContadores MermasMaquinasContadores { get; set; }
    }
}
