//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MermasAnalisisConfig
    {
        public int IdMermaAnalisisConfig { get; set; }
        public string IdLinea { get; set; }
        public decimal IMEObjetivo { get; set; }
        public bool TipoCalculoRetornable { get; set; }
    }
}
