//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MermasTurnos
    {
        public MermasTurnos()
        {
            this.MermasRegistros = new HashSet<MermasRegistros>();
        }
    
        public int IdMermaTurno { get; set; }
        public long IdTurno { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public System.DateTime FechaActualizado { get; set; }
    
        public virtual ICollection<MermasRegistros> MermasRegistros { get; set; }
    }
}
