//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MermasContadorGlobal
    {
        public MermasContadorGlobal()
        {
            this.MermasMaestroContadores = new HashSet<MermasMaestroContadores>();
        }
    
        public int IdContadorGlobal { get; set; }
        public string NombreContadorGlobal { get; set; }
    
        public virtual ICollection<MermasMaestroContadores> MermasMaestroContadores { get; set; }
    }
}
