//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MermasMaestroContadores
    {
        public MermasMaestroContadores()
        {
            this.MermasMaquinasContadores = new HashSet<MermasMaquinasContadores>();
        }
    
        public int IdMermasMaestroContadores { get; set; }
        public string ClaseMaquina { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> ContadorGlobal { get; set; }
        public decimal PorcentajeMinimo { get; set; }
        public decimal PorcentajeMaximo { get; set; }
        public string ClaseEnvase { get; set; }
        public bool CapturaAutomatica { get; set; }
        public int Orden { get; set; }
        public bool EsContadorProduccion { get; set; }
        public bool EsRechazoTotal { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public System.DateTime FechaActualizado { get; set; }
    
        public virtual MermasContadorGlobal MermasContadorGlobal { get; set; }
        public virtual ICollection<MermasMaquinasContadores> MermasMaquinasContadores { get; set; }
    }
}
