//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MermasMaquinasContadores
    {
        public MermasMaquinasContadores()
        {
            this.MermasContadores = new HashSet<MermasContadores>();
        }
    
        public int IdMermaMaquinaContador { get; set; }
        public int IdMaquina { get; set; }
        public int IdMermaMaestroContador { get; set; }
        public Nullable<decimal> PorcentajeMinimo { get; set; }
        public Nullable<decimal> PorcentajeMaximo { get; set; }
        public string ClaseEnvase { get; set; }
        public Nullable<bool> CapturaAutomatica { get; set; }
        public Nullable<int> Orden { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public System.DateTime FechaActualizado { get; set; }
    
        public virtual ICollection<MermasContadores> MermasContadores { get; set; }
        public virtual MermasMaestroContadores MermasMaestroContadores { get; set; }
    }
}
