//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MESFabEntities : DbContext
    {
        public MESFabEntities()
            : base("name=MESFabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WOPlanificadas> WOPlanificadas { get; set; }
        public virtual DbSet<TiposWO> TiposWO { get; set; }
        public virtual DbSet<Subprocesos> Subprocesos { get; set; }
        public virtual DbSet<TiposSubprocesos> TiposSubprocesos { get; set; }
        public virtual DbSet<OLTPMensajes> OLTPMensajes { get; set; }
        public virtual DbSet<vListadoWOsKOPsCoccion> vListadoWOsKOPsCoccion { get; set; }
        public virtual DbSet<KOPs> KOPs { get; set; }
        public virtual DbSet<vEstadoKOP_WO> vEstadoKOP_WO { get; set; }
        public virtual DbSet<EstadosKOP> EstadosKOP { get; set; }
        public virtual DbSet<KOPsMultivalor> KOPsMultivalor { get; set; }
        public virtual DbSet<ValoresKOPsMultivalor> ValoresKOPsMultivalor { get; set; }
        public virtual DbSet<TiposKOPMultivalor> TiposKOPMultivalor { get; set; }
        public virtual DbSet<VariablesFormulaKOP> VariablesFormulaKOP { get; set; }
        public virtual DbSet<PropiedadesWO> PropiedadesWO { get; set; }
        public virtual DbSet<MaestroKOPs> MaestroKOPs { get; set; }
        public virtual DbSet<MaestroKOPs_Mostos_Ubicacion> MaestroKOPs_Mostos_Ubicacion { get; set; }
        public virtual DbSet<ModulosSubprocesos> ModulosSubprocesos { get; set; }
        public virtual DbSet<WOs> WOs { get; set; }
        public virtual DbSet<MaestroValoresKOPsMultivalor> MaestroValoresKOPsMultivalor { get; set; }
        public virtual DbSet<MaestroKOPsMultivalor> MaestroKOPsMultivalor { get; set; }
        public virtual DbSet<vListadoWOsKOPsMultivalorCoccion> vListadoWOsKOPsMultivalorCoccion { get; set; }
        public virtual DbSet<vListadoWOsKOPsMultivalorFermentacion> vListadoWOsKOPsMultivalorFermentacion { get; set; }
        public virtual DbSet<vListadoWOsKOPsMultivalorTrasiego> vListadoWOsKOPsMultivalorTrasiego { get; set; }
        public virtual DbSet<vMaestroUbicaciones> vMaestroUbicaciones { get; set; }
        public virtual DbSet<vMaestroMateriales> vMaestroMateriales { get; set; }
        public virtual DbSet<vListadoWOsCoccion> vListadoWOsCoccion { get; set; }
    
        public virtual int API_ActualizarKOPSCalculados(Nullable<int> idOrden)
        {
            var idOrdenParameter = idOrden.HasValue ?
                new ObjectParameter("IdOrden", idOrden) :
                new ObjectParameter("IdOrden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("API_ActualizarKOPSCalculados", idOrdenParameter);
        }
    
        public virtual int spReplanificarWOCoccion(Nullable<int> idUbicacion, Nullable<bool> procesado, Nullable<int> idTipoWO)
        {
            var idUbicacionParameter = idUbicacion.HasValue ?
                new ObjectParameter("IdUbicacion", idUbicacion) :
                new ObjectParameter("IdUbicacion", typeof(int));
    
            var procesadoParameter = procesado.HasValue ?
                new ObjectParameter("Procesado", procesado) :
                new ObjectParameter("Procesado", typeof(bool));
    
            var idTipoWOParameter = idTipoWO.HasValue ?
                new ObjectParameter("IdTipoWO", idTipoWO) :
                new ObjectParameter("IdTipoWO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spReplanificarWOCoccion", idUbicacionParameter, procesadoParameter, idTipoWOParameter);
        }
    }
}
