//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MESEntities : DbContext
    {
        public MESEntities()
            : base("name=MESEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AnalisisSPI> ANALISIS_SPI { get; set; }
        public DbSet<AREAS_GESTION> AREAS_GESTION { get; set; }
        public DbSet<FUNCIONES> FUNCIONES { get; set; }
        public DbSet<PERMISOS> PERMISOS { get; set; }
        public DbSet<ParametrosPlanta_Admin> ParametrosPlanta_Admin { get; set; }
        public DbSet<TipoOrden_Fab> TipoOrden_Fab { get; set; }
        public DbSet<RecursoTipoOrden_FAB> RecursoTipoOrden_FAB { get; set; }
        public DbSet<Planta_FAB> Planta_FAB { get; set; }
        public DbSet<KOPs_FAB> KOPs_FAB { get; set; }
        public DbSet<MMLocations_FAB> MMLocations_FAB { get; set; }
        public DbSet<LoteUbicacionMaterial_FAB> LoteUbicacionMaterial_FAB { get; set; }
        public DbSet<LoteUbicacion_FAB> LoteUbicacion_FAB { get; set; }
        public DbSet<Ordenes_FAB> Ordenes_FAB { get; set; }
        public DbSet<Area_FAB> Area_FAB { get; set; }
        public DbSet<Celda_FAB> Celda_FAB { get; set; }
        public DbSet<Equipo_FAB> Equipo_FAB { get; set; }
        public DbSet<KOPs_FAB_MultiValor> KOPs_FAB_MultiValor { get; set; }
        public DbSet<KOPs_FAB_Historian> KOPs_FAB_Historian { get; set; }
        public DbSet<MaterialColor> MaterialColor { get; set; }
        public DbSet<ItemsInActiveFiltration> ItemsInActiveFiltration { get; set; }
        public DbSet<Lotes_FAB> Lotes_FAB { get; set; }
        public DbSet<Turnos> Turnos { get; set; }
        public DbSet<EstadosOrden> EstadosOrden { get; set; }
        public DbSet<CocPlanning> CocPlanning { get; set; }
        public DbSet<PackingArticleFromJDE> PackingArticleFromJDE { get; set; }
        public DbSet<PackingPO> PackingPO { get; set; }
        public DbSet<UbicacionLoteByOrden_FAB> UbicacionLoteByOrden_FAB { get; set; }
        public DbSet<MaquinasLineas> MaquinasLineas { get; set; }
        public DbSet<Ordenes> Ordenes { get; set; }
        public DbSet<Particiones> Particiones { get; set; }
        public DbSet<TiposTurno> TiposTurno { get; set; }
        public DbSet<TurnosOEE> TurnosOEE { get; set; }
        public DbSet<MaquinasLineasPlanConti> MaquinasLineasPlanConti { get; set; }
        public DbSet<TIPOS_ARRANQUE> TIPOS_ARRANQUE { get; set; }
        public DbSet<Procedimiento_FAB> Procedimiento_FAB { get; set; }
        public DbSet<BeerTypes_FAB> BeerTypes_FAB { get; set; }
        public DbSet<HighDensityBeer_FAB> HighDensityBeer_FAB { get; set; }
        public DbSet<RelHDBeer_HDBeerParameters_FAB> RelHDBeer_HDBeerParameters_FAB { get; set; }
        public DbSet<PlanningDecanting_FAB> PlanningDecanting_FAB { get; set; }
        public DbSet<ParametrosOrdenes> ParametrosOrdenes { get; set; }
        public DbSet<RelHDBeer_HDBeerParametersWP_FAB> RelHDBeer_HDBeerParametersWP_FAB { get; set; }
        public DbSet<PackingFromManugistics> PackingFromManugistics { get; set; }
        public DbSet<SalasCocciones> SalasCocciones { get; set; }
        public DbSet<Ordenes_WP> Ordenes_WP { get; set; }
        public DbSet<Ordenes_GU> Ordenes_GU { get; set; }
        public DbSet<RelPPR_COB_ArticlesParametersFIL> RelPPR_COB_ArticlesParametersFIL { get; set; }
        public DbSet<Ordenes_ENV> Ordenes_ENV { get; set; }
        public DbSet<Ordenes_FIL> Ordenes_FIL { get; set; }
        public DbSet<RelPPR_COB_ArticlesParametersPackingLineFIL> RelPPR_COB_ArticlesParametersPackingLineFIL { get; set; }
        public DbSet<Ordenes_FIL_MAT_PLANNED> Ordenes_FIL_MAT_PLANNED { get; set; }
        public DbSet<Ordenes_FIL_MAT_PRODUCED> Ordenes_FIL_MAT_PRODUCED { get; set; }
        public DbSet<PackingWo_HighBeer> PackingWo_HighBeer { get; set; }
        public DbSet<EspecificacionMateriales_FAB> EspecificacionMateriales_FAB { get; set; }
        public DbSet<ConsumosMateriales_FAB> ConsumosMateriales_FAB { get; set; }
        public DbSet<PPR_FAB> PPR_FAB { get; set; }
        public DbSet<REL_PackingWo_HighBeer> REL_PackingWo_HighBeer { get; set; }
        public DbSet<RelPackingWO_COB_ArticlesParameters> RelPackingWO_COB_ArticlesParameters { get; set; }
        public DbSet<TempNecesidadMostoWP> TempNecesidadMostoWP { get; set; }
        public DbSet<RelPackingWOHighBeer_COB_ArticlesParametersWP> RelPackingWOHighBeer_COB_ArticlesParametersWP { get; set; }
        public DbSet<RelPackingWOHighBeer_COB_ArticlesParametersFIL> RelPackingWOHighBeer_COB_ArticlesParametersFIL { get; set; }
        public DbSet<Lineas> Lineas { get; set; }
        public DbSet<TiemposArranque> TiemposArranque { get; set; }
        public DbSet<TiemposCambio> TiemposCambio { get; set; }
        public DbSet<FillersByTCP> FillersByTCP { get; set; }
        public DbSet<DeslizanteLineas> DeslizanteLineas { get; set; }
        public DbSet<AdherenciaDesviacionVolumen> AdherenciaDesviacionVolumen { get; set; }
        public DbSet<OrdenesArranque> OrdenesArranque { get; set; }
        public DbSet<OrdenesCambio> OrdenesCambio { get; set; }
        public DbSet<ParametrosLinea> ParametrosLinea { get; set; }
        public DbSet<MailConfiguration> MailConfiguration { get; set; }
        public DbSet<MailEquipmentNotification> MailEquipmentNotification { get; set; }
        public DbSet<ParametrosPRL> ParametrosPRL { get; set; }
        public DbSet<AdherenciaMotivos> AdherenciaMotivos { get; set; }
        public DbSet<DeslizanteCerveza> DeslizanteCerveza { get; set; }
        public DbSet<DeslizanteEnvasado> DeslizanteEnvasado { get; set; }
        public DbSet<ParametrosDefecto> ParametrosDefecto { get; set; }
        public DbSet<TotalesSemanaCuadroMando> TotalesSemanaCuadroMando { get; set; }
        public DbSet<DescripcionAverias> DescripcionAverias { get; set; }
        public DbSet<EquiposConstructivosEnvasado> EquiposConstructivosEnvasado { get; set; }
        public DbSet<MaquinasEnvasado> MaquinasEnvasado { get; set; }
        public DbSet<ParosPerdidas> ParosPerdidas { get; set; }
        public DbSet<ConfiguracionEmpaquetadoras> ConfiguracionEmpaquetadoras { get; set; }
        public DbSet<MermasStockVacio> MermasStockVacio { get; set; }
        public DbSet<MovimientosVacio> MovimientosVacio { get; set; }
        public DbSet<ProductosCajas> ProductosCajas { get; set; }
        public DbSet<OrdenPlanificado> OrdenPlanificado { get; set; }
        public DbSet<AdherenciaParametros> AdherenciaParametros { get; set; }
        public DbSet<ConfiguracionMaquinasCompartidas> ConfiguracionMaquinasCompartidas { get; set; }
        public DbSet<HistoricoMaquinas> HistoricoMaquinas { get; set; }
        public DbSet<StockVacioParametros> StockVacioParametros { get; set; }
        public DbSet<Equipos> Equipos { get; set; }
        public DbSet<Maquinas> Maquinas { get; set; }
        public DbSet<StockVacioPrevision> StockVacioPrevision { get; set; }
        public DbSet<VideowallPantallas> VideowallPantallas { get; set; }
        public DbSet<VideowallPantallasLineas> VideowallPantallasLineas { get; set; }
        public DbSet<DeslizanteEnvasadoHl> DeslizanteEnvasadoHl { get; set; }
        public DbSet<StockVacioMinimosMaximos> StockVacioMinimosMaximos { get; set; }
        public DbSet<JustificacionParosMotivos> JustificacionParosMotivos { get; set; }
        public DbSet<GraficaProduccionTeoricaVSReal> GraficaProduccionTeoricaVSReal { get; set; }
        public DbSet<VideowallConfiguracion> VideowallConfiguracion { get; set; }
        public DbSet<DeslizanteFormatos> DeslizanteFormatos { get; set; }
        public DbSet<DeslizanteGeneral> DeslizanteGeneral { get; set; }
        public DbSet<DeslizanteProductos> DeslizanteProductos { get; set; }
        public DbSet<DiasSemanaDeslizante> DiasSemanaDeslizante { get; set; }
        public DbSet<DuotankMatriculas> DuotankMatriculas { get; set; }
        public DbSet<DuotankZonasCarga> DuotankZonasCarga { get; set; }
        public DbSet<RelacionCodArticuloCodCaja> RelacionCodArticuloCodCaja { get; set; }
        public DbSet<LineasDobleSalidaAsignacion> LineasDobleSalidaAsignacion { get; set; }
        public DbSet<LineasDobleSalidaConfiguracion> LineasDobleSalidaConfiguracion { get; set; }
        public DbSet<Zonas> Zonas { get; set; }
        public DbSet<EstructuraPermisos> EstructuraPermisos { get; set; }
        public DbSet<SIGI_SecuenciacionMES> SIGI_SecuenciacionMES { get; set; }
        public DbSet<SIGI_SecuenciacionSIGI> SIGI_SecuenciacionSIGI { get; set; }
        public DbSet<LineasProductos> LineasProductos { get; set; }
        public DbSet<MantenimientoParosRelaciones> MantenimientoParosRelaciones { get; set; }
        public DbSet<SIGI_Configuracion> SIGI_Configuracion { get; set; }
        public DbSet<TipoAveria> TipoAveria { get; set; }
        public DbSet<MermasContadorGlobal> MermasContadorGlobal { get; set; }
        public DbSet<PerroGuardian> PerroGuardian { get; set; }
        public DbSet<ConfiguracionVisualizacionColumnas> ConfiguracionVisualizacionColumnas { get; set; }
        public DbSet<MailMalaGestionWOLineas> MailMalaGestionWOLineas { get; set; }
        public DbSet<MantenimientoCambiosEstados> MantenimientoCambiosEstados { get; set; }
        public DbSet<MantenimientoEstados> MantenimientoEstados { get; set; }
        public DbSet<AdherenciaDesviacionSecuencia> AdherenciaDesviacionSecuencia { get; set; }
        public DbSet<AdherenciaDesviacionCongelado> AdherenciaDesviacionCongelado { get; set; }
        public DbSet<MensajeAdministracion> MensajeAdministracion { get; set; }
        public DbSet<PicosEnvasado> PicosEnvasado { get; set; }
        public DbSet<SIGI_BloqueoPaletsParoLlenadora> SIGI_BloqueoPaletsParoLlenadora { get; set; }
        public DbSet<MantenimientoDatosValidacionArranqueOT> MantenimientoDatosValidacionArranqueOT { get; set; }
        public DbSet<vMantenimientoConfMaquinasValidacionArranque> vMantenimientoConfMaquinasValidacionArranque { get; set; }
        public DbSet<MantenimientoConfMaquinasValidacionArranque> MantenimientoConfMaquinasValidacionArranque { get; set; }
        public DbSet<MantenimientoEquivalenciaCausas> MantenimientoEquivalenciaCausas { get; set; }
        public DbSet<OEEPlanificaciones> OEEPlanificaciones { get; set; }
        public DbSet<vt_OEEPlanificaciones> vt_OEEPlanificaciones { get; set; }
        public DbSet<MailPartesCalidadNoValidos> MailPartesCalidadNoValidos { get; set; }
        public DbSet<MailGroup> MailGroup { get; set; }
        public DbSet<MailNotification> MailNotification { get; set; }
        public DbSet<MailMalaGestionWO> MailMalaGestionWO { get; set; }
        public DbSet<MaestroAreasFabricacion> MaestroAreasFabricacion { get; set; }
        public DbSet<MaestroEquiposFabricacion> MaestroEquiposFabricacion { get; set; }
        public DbSet<MaestroGruposConstructivosFabricacion> MaestroGruposConstructivosFabricacion { get; set; }
        public DbSet<MaestroRepuestosFabricacion> MaestroRepuestosFabricacion { get; set; }
        public DbSet<MaestroZonasFabricacion> MaestroZonasFabricacion { get; set; }
        public DbSet<MantenimientoIntervenciones> MantenimientoIntervenciones { get; set; }
        public DbSet<DuotankHistorico> DuotankHistorico { get; set; }
        public DbSet<MailPartesCalidadPendientes> MailPartesCalidadPendientes { get; set; }
        public DbSet<MermasContadores> MermasContadores { get; set; }
        public DbSet<MermasRegistros> MermasRegistros { get; set; }
        public DbSet<MermasTurnos> MermasTurnos { get; set; }
        public DbSet<vMermasRegistros> vMermasRegistros { get; set; }
        public DbSet<vMermasTurnos> vMermasTurnos { get; set; }
        public DbSet<MermasMaestroContadores> MermasMaestroContadores { get; set; }
        public DbSet<MermasMaquinasContadores> MermasMaquinasContadores { get; set; }
        public DbSet<TurnosConBreak> TurnosConBreak { get; set; }
        public DbSet<vMermasMaquinasContadores> vMermasMaquinasContadores { get; set; }
        public DbSet<OEEPlanificacionConfig> OEEPlanificacionConfig { get; set; }
        public DbSet<Materiales_FAB> Materiales_FAB { get; set; }
        public DbSet<MermasAnalisisConfig> MermasAnalisisConfig { get; set; }
    
        public virtual int MES_ActualizaWOEquiposZona(string idZona, string idOrden)
        {
            var idZonaParameter = idZona != null ?
                new ObjectParameter("idZona", idZona) :
                new ObjectParameter("idZona", typeof(string));
    
            var idOrdenParameter = idOrden != null ?
                new ObjectParameter("idOrden", idOrden) :
                new ObjectParameter("idOrden", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MES_ActualizaWOEquiposZona", idZonaParameter, idOrdenParameter);
        }
    
        public virtual int SIT_ExecuteJobMESJDE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SIT_ExecuteJobMESJDE");
        }
    }
}
