//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMLocations_FAB
    {
        public int LocPK { get; set; }
        public string LocID { get; set; }
        public int LocTypePK { get; set; }
        public string LocAlias { get; set; }
        public string Descript { get; set; }
        public Nullable<int> ParentLocPK { get; set; }
        public Nullable<int> CommonLocPK { get; set; }
        public string LocPath { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<short> SrvCrtBias { get; set; }
        public string LastUser { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<short> SrvLstBias { get; set; }
        public byte[] LocalInfo { get; set; }
        public string ContextID { get; set; }
        public System.Guid RowGuid { get; set; }
        public Nullable<long> RowVerNum { get; set; }
    }
}
