//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulosSubprocesos
    {
        public int IdModuloSubproceso { get; set; }
        public string Modulo { get; set; }
        public int IdTipoSubproceso { get; set; }
        public string CodigoWO { get; set; }
        public int IdZona { get; set; }
    
        public virtual TiposSubprocesos TiposSubprocesos { get; set; }
    }
}
