//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosVacio
    {
        public long Id { get; set; }
        public string IdMovimiento { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
        public string IdCaja { get; set; }
        public string IdOrden { get; set; }
        public int LineaOrden { get; set; }
        public int StockInicial { get; set; }
        public int CantidadMovimiento { get; set; }
        public int StockFinal { get; set; }
    }
}
