//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEEPlanificaciones
    {
        public long IdOEEPlanificaciones { get; set; }
        public string IdLinea { get; set; }
        public Nullable<long> IdProducto { get; set; }
        public Nullable<bool> InhabilitarCalculoAC { get; set; }
        public Nullable<double> TiempoArranque { get; set; }
        public Nullable<double> TiempoCambio { get; set; }
        public Nullable<double> MediaAC { get; set; }
        public Nullable<bool> InhabilitarCalculoOEE { get; set; }
        public Nullable<double> OEEPlanificado { get; set; }
        public Nullable<double> CPBsHora { get; set; }
        public System.DateTime Creado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> Actualizado { get; set; }
        public string ActualizadoPor { get; set; }
        public decimal AjusteOEE { get; set; }
        public decimal CPBMDBY { get; set; }
        public string Color { get; set; }
        public decimal OEEFinalPlanificacion { get; set; }
    }
}
