//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OLTPMensajes
    {
        public int IdOLTPMensaje { get; set; }
        public string Modulo { get; set; }
        public string Lote { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public string Valor { get; set; }
        public string Unidad { get; set; }
        public int FracSec { get; set; }
        public int Procesado { get; set; }
        public System.DateTime FechaLote { get; set; }
        public Nullable<System.DateTime> FechaActualizado { get; set; }
    }
}
