//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes_FAB
    {
        public int Cod_Orden { get; set; }
        public string ID_Orden { get; set; }
        public string Des_Orden { get; set; }
        public string Cod_Material { get; set; }
        public Nullable<double> Cantidad_Material { get; set; }
        public string UOM_Material { get; set; }
        public Nullable<System.DateTime> Tiempo_Inicio_Estimado { get; set; }
        public Nullable<System.DateTime> Tiempo_Inicio_EstimadoUTC { get; set; }
        public Nullable<System.DateTime> Tiempo_Fin_Estimado { get; set; }
        public Nullable<System.DateTime> Tiempo_Fin_EstimadoUTC { get; set; }
        public Nullable<System.DateTime> Tiempo_Inicio_Real { get; set; }
        public Nullable<System.DateTime> Tiempo_Inicio_RealUTC { get; set; }
        public Nullable<System.DateTime> Tiempo_Fin_Real { get; set; }
        public Nullable<System.DateTime> Tiempo_Fin_RealUTC { get; set; }
        public string TipoOrden { get; set; }
        public string EquipoOrden { get; set; }
        public int IdEstado { get; set; }
        public string Estado { get; set; }
        public string pkLote { get; set; }
        public Nullable<double> CantidadProducida { get; set; }
        public string ppr_name { get; set; }
        public string Transition_Group { get; set; }
    }
}
