//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesCambio
    {
        public string Id { get; set; }
        public string IdLinea { get; set; }
        public Nullable<int> Linea { get; set; }
        public string NumLineaDescripcion { get; set; }
        public string DescripcionLinea { get; set; }
        public Nullable<System.DateTime> InicioReal { get; set; }
        public Nullable<System.DateTime> InicioUTC { get; set; }
        public string TipoTurnoId { get; set; }
        public string TipoTurno { get; set; }
        public System.DateTime FechaTurno { get; set; }
        public string OrdenSaliente { get; set; }
        public string IDProductoSaliente { get; set; }
        public string ProductoSaliente { get; set; }
        public string OrdenEntrante { get; set; }
        public string IDProductoEntrante { get; set; }
        public string ProductoEntrante { get; set; }
        public Nullable<int> MinutosFinal1 { get; set; }
        public Nullable<int> MinutosFinal2 { get; set; }
        public int MinutosObjetivo1 { get; set; }
        public int MinutosObjetivo2 { get; set; }
        public Nullable<long> ID_CAMBIO { get; set; }
        public string EstadoAct { get; set; }
        public string IndicadorLlenadora { get; set; }
        public string IndicadorPaletizadora { get; set; }
        public int TiempoPreactor { get; set; }
    }
}
