//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenPlanificado
    {
        public int Id { get; set; }
        public string Material { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public Nullable<System.DateTime> InicioPlanificado { get; set; }
        public Nullable<System.DateTime> FinPlanificado { get; set; }
        public Nullable<bool> Arrancado { get; set; }
        public string CodigoOrden { get; set; }
        public string Nota { get; set; }
        public string TipoOrden { get; set; }
    }
}
