//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingFromManugistics
    {
        public int ID { get; set; }
        public string codigo { get; set; }
        public string descript { get; set; }
        public Nullable<double> quantity { get; set; }
        public string Czh { get; set; }
    }
}
