//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosDefecto
    {
        public long IdObj { get; set; }
        public Nullable<int> NumeroLinea { get; set; }
        public string DescripcionLinea { get; set; }
        public string NumeroLineaDescripcion { get; set; }
        public string FormatoComunCodigo { get; set; }
        public string FormatoComunNombre { get; set; }
        public Nullable<int> VelocidadNominal { get; set; }
        public Nullable<float> OEECritico { get; set; }
        public Nullable<float> OEEObjetivo { get; set; }
        public Nullable<float> OEEPreactor { get; set; }
        public string FormatoComun { get; set; }
        public Nullable<int> VelocidadNominalMaqLimitante { get; set; }
    }
}
