//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosOrdenes
    {
        public string IdOrden { get; set; }
        public int IdSubOrden { get; set; }
        public int PaletsProducidos { get; set; }
        public int CajasProducidas { get; set; }
        public int EnvasesProducidos { get; set; }
        public int RechazosALlenadora { get; set; }
        public int RechazosAClasificador { get; set; }
        public int RechazosAProductoTerminado { get; set; }
        public int RechazosAVacios { get; set; }
        public int PicosCajas { get; set; }
    }
}
