//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosPlanta_Admin
    {
        public long Id { get; set; }
        public Nullable<int> IdLinea { get; set; }
        public Nullable<short> IdParametro { get; set; }
        public string NombreParametro { get; set; }
        public string DescripcionParametro { get; set; }
        public string TipoValor { get; set; }
        public Nullable<float> VALOR_FLOAT { get; set; }
        public Nullable<int> VALOR_INT { get; set; }
        public string VALOR_STRING { get; set; }
        public string Regla { get; set; }
    }
}
