//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosLinea
    {
        public Nullable<long> PK { get; set; }
        public string PPR { get; set; }
        public string idLinea { get; set; }
        public string Producto { get; set; }
        public Nullable<int> VelocidadNominal { get; set; }
        public Nullable<float> OEECritico { get; set; }
        public Nullable<float> OEEObjetivo { get; set; }
        public Nullable<float> OEECalculado { get; set; }
        public Nullable<float> OEEPreactor { get; set; }
        public Nullable<short> InhabilitarCalculo { get; set; }
        public Nullable<int> VelocidadNominalMaqLimitante { get; set; }
    }
}
