//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParosPerdidas
    {
        public long Id { get; set; }
        public Nullable<short> IdTipoParoPerdida { get; set; }
        public string TipoParoPerdida { get; set; }
        public Nullable<int> IdLinea { get; set; }
        public string NumeroLineaDescripcion { get; set; }
        public string DescLinea { get; set; }
        public Nullable<int> Turno { get; set; }
        public System.DateTime FechaTurno { get; set; }
        public string IdTipoTurno { get; set; }
        public string NombreTipoTurno { get; set; }
        public Nullable<System.DateTime> FinTurno { get; set; }
        public Nullable<System.DateTime> INICIO { get; set; }
        public Nullable<System.DateTime> FIN { get; set; }
        public Nullable<System.DateTime> InicioLocal { get; set; }
        public Nullable<System.DateTime> FinLocal { get; set; }
        public string EquipoId { get; set; }
        public string EquipoNombre { get; set; }
        public string MotivoId { get; set; }
        public string MotivoNombre { get; set; }
        public string CausaId { get; set; }
        public string CausaNombre { get; set; }
        public Nullable<short> Justificado { get; set; }
        public string Observaciones { get; set; }
        public string MaquinaCausaId { get; set; }
        public string MaquinaCausaNombre { get; set; }
        public string EquipoConstructivoId { get; set; }
        public string EquipoConstructivoNombre { get; set; }
        public string Descripcion { get; set; }
        public int NumeroParosMenores { get; set; }
        public Nullable<double> DuracionParosMenores { get; set; }
        public Nullable<double> DuracionParoMayor { get; set; }
        public Nullable<double> DuracionBajaVelocidad { get; set; }
        public string EquipoDescripcion { get; set; }
        public double Duracion { get; set; }
    }
}
