//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Particiones
    {
        public string Id { get; set; }
        public Nullable<int> IdSubOrden { get; set; }
        public Nullable<System.DateTime> FecIniEstimada { get; set; }
        public Nullable<System.DateTime> FecFinEstimada { get; set; }
        public Nullable<System.DateTime> FecIniReal { get; set; }
        public Nullable<System.DateTime> FecFinReal { get; set; }
        public string IdProducto { get; set; }
        public Nullable<double> CantidadPlanificada { get; set; }
        public Nullable<double> CantidadProducida { get; set; }
        public string EstadoAct { get; set; }
        public int IdEstadoAct { get; set; }
        public string EstadoAnt { get; set; }
        public Nullable<int> IdEstadoAnt { get; set; }
        public string Linea { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FecHorAct { get; set; }
        public double VelocidadNominal { get; set; }
        public double OEEObjetivo { get; set; }
        public double OEECritico { get; set; }
        public string CodigoJDE { get; set; }
        public string PPR { get; set; }
        public int Rechazos { get; set; }
        public double OEE { get; set; }
        public double Disponibilidad { get; set; }
        public double Eficiencia { get; set; }
        public double Calidad { get; set; }
        public double RendMecanico { get; set; }
        public int EnvasesPorPalet { get; set; }
        public int CajasPorPalet { get; set; }
        public decimal HectolitrosProducto { get; set; }
        public Nullable<int> PicosCajas { get; set; }
        public Nullable<double> OEEPreactor { get; set; }
        public int WoStatusChangeOnGoing { get; set; }
    }
}
