//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISOS
    {
        public int ID_PERMISO { get; set; }
        public string ID_ROL { get; set; }
        public int ID_FUNCION { get; set; }
    
        public virtual FUNCIONES FUNCIONES { get; set; }
    }
}
