//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerroGuardian
    {
        public int IdProceso { get; set; }
        public string DescripcionProceso { get; set; }
        public Nullable<System.DateTime> FechaUltimaEjecucion { get; set; }
        public bool Activo { get; set; }
        public string MensajeMail { get; set; }
        public string Destinatarios { get; set; }
        public int MaximoTiempoInactivo { get; set; }
    }
}
