//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PicosEnvasado
    {
        public int IdPico { get; set; }
        public string SSCC { get; set; }
        public int SHC_WORK_SCHED_DAY_PK { get; set; }
        public string IdOrden { get; set; }
        public string IdParticion { get; set; }
        public int Cantidad { get; set; }
        public Nullable<System.DateTime> Actualizado { get; set; }
    }
}
