//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedimiento_FAB
    {
        public int Cod_Procedimiento { get; set; }
        public string ID_Procedimiento { get; set; }
        public string Des_Procedimiento { get; set; }
        public int Cod_Orden { get; set; }
        public string ID_Orden { get; set; }
        public string ID_Material { get; set; }
        public Nullable<double> Cantidad_Material { get; set; }
        public string ID_Uom { get; set; }
        public string Estado_Procedimiento { get; set; }
        public Nullable<int> Orden_Procedimiento { get; set; }
        public string ID_Equipo { get; set; }
        public string Des_Equipo { get; set; }
        public Nullable<System.DateTime> Tiempo_Inicio { get; set; }
        public Nullable<System.DateTime> Tiempo_InicioUTC { get; set; }
        public Nullable<System.DateTime> Tiempo_Fin { get; set; }
        public Nullable<System.DateTime> Tiempo_FinUTC { get; set; }
        public int IDEstado_Procedimiento { get; set; }
    }
}
