//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropiedadesWO
    {
        public int IdPropiedadWO { get; set; }
        public string DescPropiedadWO { get; set; }
        public string ValorPropiedadWO { get; set; }
        public string TipoDatoPropiedadWO { get; set; }
        public int IdWO { get; set; }
        public Nullable<System.DateTime> FechaActualizado { get; set; }
    
        public virtual WOs WOs { get; set; }
    }
}
