//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_PackingWo_HighBeer
    {
        public int ID { get; set; }
        public string PackingArticleID { get; set; }
        public string Czh { get; set; }
        public string PPR { get; set; }
        public string Description { get; set; }
        public string CZAEnv { get; set; }
        public string Mosto { get; set; }
    }
}
