//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelHDBeer_HDBeerParametersWP_FAB
    {
        public long ID { get; set; }
        public string Beer { get; set; }
        public string DefID { get; set; }
        public string MaterialCod { get; set; }
        public string TipoCerveza { get; set; }
        public Nullable<double> MermaFermentacion { get; set; }
        public Nullable<double> HlPorCoccion { get; set; }
    }
}
