//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelPackingWOHighBeer_COB_ArticlesParametersWP
    {
        public Nullable<long> ID { get; set; }
        public string DefID { get; set; }
        public string PackingArticleID { get; set; }
        public string Czh { get; set; }
        public string CZAEnv { get; set; }
        public string Mosto { get; set; }
        public Nullable<double> MermaEnvasado { get; set; }
        public Nullable<double> MermaFiltracion { get; set; }
        public Nullable<double> FiltracionRecuperado { get; set; }
        public Nullable<double> Dilucion { get; set; }
    }
}
