//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelPPR_COB_ArticlesParametersFIL
    {
        public Nullable<long> ID { get; set; }
        public string defid { get; set; }
        public string descript { get; set; }
        public Nullable<double> MermaEnvasado { get; set; }
    }
}
