//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGI_SecuenciacionMES
    {
        public long Id { get; set; }
        public string IdLinea { get; set; }
        public string IdProducto { get; set; }
        public string DescripcionProducto { get; set; }
        public System.DateTime FechaInicioPlanificado { get; set; }
        public string WO { get; set; }
        public string EstadoWO { get; set; }
    }
}
