//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGI_Configuracion
    {
        public int Id { get; set; }
        public int IdEtiquetaSIGI { get; set; }
        public string LineaSIGI { get; set; }
        public string LineaMES { get; set; }
        public string DescripcionLinea { get; set; }
        public bool ConPlanificacion { get; set; }
        public bool TransferenciaAutomatica { get; set; }
        public bool HabilitarProdSimultanea { get; set; }
        public bool ValorProdSimultanea { get; set; }
    }
}
