//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGI_BloqueoPaletsParoLlenadora
    {
        public int IdBloqueo { get; set; }
        public string IdLinea { get; set; }
        public bool Habilitado { get; set; }
        public int DuracionParoMinutos { get; set; }
        public int NumPalets { get; set; }
        public int DuracionLlenadoraEtiquetadoraMinutos { get; set; }
        public int IdUltimoParo { get; set; }
    }
}
