//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subprocesos
    {
        public int IdSubproceso { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.DateTime> FechaActualizado { get; set; }
        public string LoteSAI { get; set; }
        public int IdWO { get; set; }
        public int IdTipoSubproceso { get; set; }
    
        public virtual TiposSubprocesos TiposSubprocesos { get; set; }
        public virtual WOs WOs { get; set; }
    }
}
