//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiemposArranque
    {
        public long IdTiempoArranque { get; set; }
        public string LINEA { get; set; }
        public string IdProductoEntrante { get; set; }
        public string ProductoEntrante { get; set; }
        public Nullable<short> TipoArranque { get; set; }
        public Nullable<int> Tobj1 { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Tobj2 { get; set; }
        public Nullable<int> Tm { get; set; }
        public Nullable<int> TIEMPO_CALCULADO_2 { get; set; }
        public Nullable<int> TIEMPO_PREACTOR { get; set; }
        public string DescArranque { get; set; }
        public Nullable<short> InhabilitarCalculo { get; set; }
    }
}
