//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOS_ARRANQUE
    {
        public Nullable<short> ID_ARRANQUE { get; set; }
        public string DESC_ARRANQUE { get; set; }
        public long IdObj { get; set; }
    }
}
