//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposSubprocesos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposSubprocesos()
        {
            this.Subprocesos = new HashSet<Subprocesos>();
            this.MaestroKOPs = new HashSet<MaestroKOPs>();
            this.ModulosSubprocesos = new HashSet<ModulosSubprocesos>();
            this.MaestroKOPsMultivalor = new HashSet<MaestroKOPsMultivalor>();
        }
    
        public int IdTipoSubproceso { get; set; }
        public string DescSubProceso { get; set; }
        public short Orden { get; set; }
        public int IdTipoWO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subprocesos> Subprocesos { get; set; }
        public virtual TiposWO TiposWO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaestroKOPs> MaestroKOPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModulosSubprocesos> ModulosSubprocesos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaestroKOPsMultivalor> MaestroKOPsMultivalor { get; set; }
    }
}
