//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoAveria
    {
        public TipoAveria()
        {
            this.MantenimientoEquivalenciaCausas = new HashSet<MantenimientoEquivalenciaCausas>();
            this.MantenimientoIntervenciones = new HashSet<MantenimientoIntervenciones>();
        }
    
        public int IdTipoAveria { get; set; }
        public string DescripcionAveria { get; set; }
        public int CodigoJDE { get; set; }
    
        public virtual ICollection<MantenimientoEquivalenciaCausas> MantenimientoEquivalenciaCausas { get; set; }
        public virtual ICollection<MantenimientoIntervenciones> MantenimientoIntervenciones { get; set; }
    }
}
