//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalesSemanaCuadroMando
    {
        public long Id { get; set; }
        public string Linea { get; set; }
        public int PaletsTurno { get; set; }
        public int EnvasesTurno { get; set; }
        public float OEETurno { get; set; }
        public int PaletsWO { get; set; }
        public int CPBWO { get; set; }
        public int EnvasesWO { get; set; }
        public float OEEWO { get; set; }
    }
}
