//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turnos
    {
        public int Id { get; set; }
        public string Linea { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> InicioTurno { get; set; }
        public Nullable<System.DateTime> FinTurno { get; set; }
        public string IdTipoTurno { get; set; }
        public string Turno { get; set; }
        public Nullable<long> ID_Ordenado_Turno { get; set; }
        public System.DateTime FechaActualizado { get; set; }
    }
}
