//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UbicacionLoteByOrden_FAB
    {
        public string LoteMes { get; set; }
        public Nullable<double> InitQuantity { get; set; }
        public Nullable<double> Quantity { get; set; }
        public int LocPK { get; set; }
        public string LOCID { get; set; }
        public string LocPath { get; set; }
        public Nullable<int> ParentLocPK { get; set; }
        public string Descripcion { get; set; }
        public string ID_Orden { get; set; }
        public Nullable<System.DateTime> Tiempo_Inicio_Real { get; set; }
        public Nullable<System.DateTime> Tiempo_Fin_Real { get; set; }
        public string Estado { get; set; }
        public string Cod_Material { get; set; }
        public string pkLote { get; set; }
    }
}
