//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValoresKOPsMultivalor
    {
        public int IdValorKOPMultivalor { get; set; }
        public string ValorMin { get; set; }
        public string Valor { get; set; }
        public string ValorMax { get; set; }
        public Nullable<System.DateTime> FechaActualizado { get; set; }
        public int IdKOPMultivalor { get; set; }
        public int IdMaestroValorKOPMultivalor { get; set; }
        public int IdEstadoValorKOP { get; set; }
    
        public virtual KOPsMultivalor KOPsMultivalor { get; set; }
        public virtual MaestroValoresKOPsMultivalor MaestroValoresKOPsMultivalor { get; set; }
    }
}
