//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariablesFormulaKOP
    {
        public int IdVariableFormulaKOP { get; set; }
        public int IdMaestroKOP { get; set; }
        public int IdFormulaCalculoKOP { get; set; }
        public int IdMaestroKOPVariable { get; set; }
        public string VariableKOP { get; set; }
        public Nullable<System.DateTime> FechaActualizado { get; set; }
    
        public virtual MaestroKOPs MaestroKOPs { get; set; }
        public virtual MaestroKOPs MaestroKOPs1 { get; set; }
    }
}
