//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideowallConfiguracion
    {
        public int Id { get; set; }
        public int IdPantalla { get; set; }
        public string Pagina { get; set; }
        public bool Visible { get; set; }
        public int Duracion { get; set; }
    }
}
