//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vListadoWOsCoccion
    {
        public int IdWO { get; set; }
        public string CodWO { get; set; }
        public string LoteMES { get; set; }
        public Nullable<System.DateTime> FechaInicioPlan { get; set; }
        public Nullable<System.DateTime> FechaFinPlan { get; set; }
        public Nullable<decimal> CantidadPlan { get; set; }
        public Nullable<System.DateTime> FechaInicioReal { get; set; }
        public Nullable<System.DateTime> FechaFinReal { get; set; }
        public Nullable<decimal> CantidadReal { get; set; }
        public string NotasWO { get; set; }
        public int IdUbicacion { get; set; }
        public string DescZona { get; set; }
        public int IdTipoWO { get; set; }
        public string DescTipoWO { get; set; }
        public int IdEstadoWO { get; set; }
        public string DescEstadoWO { get; set; }
        public string ColorEstadoWO { get; set; }
        public int IdEstadoLIMS { get; set; }
        public string DescEstadoLIMS { get; set; }
        public string ColorEstadoLIMS { get; set; }
        public Nullable<int> NCoccion { get; set; }
        public Nullable<double> ExtractoSeco { get; set; }
        public Nullable<double> EficienciaCoccion { get; set; }
        public string IdMaterial { get; set; }
        public string DescMaterial { get; set; }
        public string UdMedida { get; set; }
        public int IdEstadoKOP { get; set; }
        public string ColorEstadoKOP { get; set; }
        public string DescEstadoKOP { get; set; }
        public bool Recalcular { get; set; }
        public Nullable<System.DateTime> FechaActualizado { get; set; }
        public int Anio { get; set; }
    }
}
