//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vListadoWOsKOPsCoccion
    {
        public int IdWO { get; set; }
        public string CodWO { get; set; }
        public bool Recalcular { get; set; }
        public int IdTipoSubproceso { get; set; }
        public string DescSubProceso { get; set; }
        public int IdKOP { get; set; }
        public string CodKOP { get; set; }
        public string DescKOP { get; set; }
        public string MensajeKOP { get; set; }
        public string ValorMin { get; set; }
        public string Valor { get; set; }
        public string ValorMax { get; set; }
        public string TipodatoKOP { get; set; }
        public string Unidad { get; set; }
        public int IdTipoKOP { get; set; }
        public string DescTipoKOP { get; set; }
        public int IdEstadoKOP { get; set; }
        public string DescEstadoKOP { get; set; }
        public string ColorEstadoKOP { get; set; }
        public bool Editable { get; set; }
        public Nullable<System.DateTime> FechaActualizado { get; set; }
    }
}
