//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vListadoWOsKOPsMultivalorCoccion
    {
        public int IdWO { get; set; }
        public string CodWO { get; set; }
        public bool Recalcular { get; set; }
        public int IdTipoSubproceso { get; set; }
        public string DescSubProceso { get; set; }
        public int IdKOPMultivalor { get; set; }
        public int IdMaestroKOPMultivalor { get; set; }
        public string CodKOP { get; set; }
        public string DescKOP { get; set; }
        public string MensajeKOP { get; set; }
        public string TipodatoMaestroKOP { get; set; }
        public string Unidad { get; set; }
        public int IdTipoKOPMultivalor { get; set; }
        public string DescTipoKOPMultivalor { get; set; }
        public int IdEstadoKOP { get; set; }
        public string DescEstadoKOP { get; set; }
        public string ColorEstadoKOP { get; set; }
        public int IdValorKOPMultivalor { get; set; }
        public string ValorMin { get; set; }
        public string Valor { get; set; }
        public string ValorMax { get; set; }
        public int Posicion { get; set; }
        public int IdEstadoValorKOP { get; set; }
        public string ColorEstadoValorKOP { get; set; }
        public Nullable<System.DateTime> FechaActualizado { get; set; }
    }
}
