//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMaestroMateriales
    {
        public string IdMaterial { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string IdClase { get; set; }
        public string Clase { get; set; }
        public string Version { get; set; }
        public string Status { get; set; }
        public string UdMedida { get; set; }
        public Nullable<System.DateTime> F_EfectivoDesde { get; set; }
        public Nullable<System.DateTime> F_EfectivoDesdeUTC { get; set; }
        public Nullable<System.DateTime> F_EfectivoHasta { get; set; }
        public Nullable<System.DateTime> F_EfectivoHastaUTC { get; set; }
        public Nullable<bool> EnUso { get; set; }
        public string Autor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacionUTC { get; set; }
        public Nullable<System.DateTime> FechaUltCreacion { get; set; }
        public Nullable<System.DateTime> FechaUltCreacionUTC { get; set; }
        public string ModificadoPor { get; set; }
        public string InfoAdicional { get; set; }
        public string Tipo { get; set; }
        public string DescTipo { get; set; }
        public Nullable<int> PK_Material { get; set; }
        public string BOM { get; set; }
        public string Origen { get; set; }
    }
}
