//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMaestroUbicaciones
    {
        public int IdUbicacion { get; set; }
        public string CodUbicacion { get; set; }
        public string DescUbicacion { get; set; }
        public Nullable<int> IdTipoUbicacion { get; set; }
        public string DescTipoUbicacion { get; set; }
        public string EnumDescTipoUbicacion { get; set; }
        public Nullable<int> IdAlmacen { get; set; }
        public string DescAlmacen { get; set; }
        public Nullable<int> IdZonaUbicacion { get; set; }
        public Nullable<int> IdZona { get; set; }
        public string DescZona { get; set; }
        public Nullable<int> IdTipoZona { get; set; }
        public string DescTipoZona { get; set; }
        public string IdClaseMaterial { get; set; }
    }
}
