//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMermasTurnos
    {
        public int IdMermaTurno { get; set; }
        public long IdTurno { get; set; }
        public string IdLinea { get; set; }
        public System.DateTime FechaTurno { get; set; }
        public Nullable<int> IdTipoTurno { get; set; }
        public string TipoTurno { get; set; }
        public System.DateTime FechaActualizado { get; set; }
    }
}
