//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMermasMaquinasContadores
    {
        public Nullable<int> IdMermaMaquinaContador { get; set; }
        public int IdMermasMaestroContadores { get; set; }
        public string IdLinea { get; set; }
        public int IdMaquina { get; set; }
        public string CodigoMaquina { get; set; }
        public string ClaseMaquina { get; set; }
        public string DescripcionMaquina { get; set; }
        public string Contador { get; set; }
        public Nullable<int> ContadorGlobal { get; set; }
        public string ContadorGlobalNombre { get; set; }
        public int Orden { get; set; }
        public decimal PorcentajeMinimo { get; set; }
        public decimal PorcentajeMaximo { get; set; }
        public string ClaseEnvase { get; set; }
        public bool CapturaAutomatica { get; set; }
        public bool EsProduccion { get; set; }
        public bool EsRechazoTotal { get; set; }
        public bool Incluido { get; set; }
        public bool Activo { get; set; }
        public bool ActivoMaestro { get; set; }
    }
}
