//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMermasRegistros
    {
        public int IdMermaTurno { get; set; }
        public int IdMermaRegistro { get; set; }
        public long IdTurno { get; set; }
        public int IdMaquina { get; set; }
        public string CodigoMaquina { get; set; }
        public string DescripcionMaquina { get; set; }
        public string ClaseMaquina { get; set; }
        public int CodigoProveedor { get; set; }
        public string DescripcionProveedor { get; set; }
        public string Observaciones { get; set; }
        public string WO { get; set; }
        public int IdProducto { get; set; }
        public string DescripcionProducto { get; set; }
        public System.DateTime FechaCreado { get; set; }
        public System.DateTime FechaActualizado { get; set; }
    }
}
