//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOPlanificadas
    {
        public int IdWOPlanificada { get; set; }
        public Nullable<System.DateTime> FechaInicioPlan { get; set; }
        public Nullable<System.DateTime> FechaFinPlan { get; set; }
        public Nullable<decimal> CantidadPlan { get; set; }
        public string NotasWO { get; set; }
        public bool Procesado { get; set; }
        public int IdUbicacionOrigen { get; set; }
        public Nullable<int> IdUbicacionDestino { get; set; }
        public int IdTipoWO { get; set; }
        public Nullable<int> IdWO { get; set; }
        public Nullable<System.DateTime> FechaActualizado { get; set; }
        public string IdMaterial { get; set; }
        public Nullable<int> IdZonaOrigen { get; set; }
    
        public virtual TiposWO TiposWO { get; set; }
        public virtual WOs WOs { get; set; }
    }
}
