//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WOs()
        {
            this.KOPs = new HashSet<KOPs>();
            this.KOPsMultivalor = new HashSet<KOPsMultivalor>();
            this.PropiedadesWO = new HashSet<PropiedadesWO>();
            this.Subprocesos = new HashSet<Subprocesos>();
            this.WOPlanificadas = new HashSet<WOPlanificadas>();
        }
    
        public int IdWO { get; set; }
        public string CodWO { get; set; }
        public string LoteMES { get; set; }
        public Nullable<System.DateTime> FechaInicioPlan { get; set; }
        public Nullable<System.DateTime> FechaFinPlan { get; set; }
        public Nullable<decimal> CantidadPlan { get; set; }
        public Nullable<System.DateTime> FechaInicioReal { get; set; }
        public Nullable<System.DateTime> FechaFinReal { get; set; }
        public Nullable<decimal> CantidadReal { get; set; }
        public string NotasWO { get; set; }
        public int IdTipoWO { get; set; }
        public int IdEstadoWO { get; set; }
        public int IdEstadoLIMS { get; set; }
        public Nullable<System.DateTime> FechaActualizado { get; set; }
        public bool Recalcular { get; set; }
        public int NumWO { get; set; }
        public int Anio { get; set; }
        public int IdUbicacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOPs> KOPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOPsMultivalor> KOPsMultivalor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropiedadesWO> PropiedadesWO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subprocesos> Subprocesos { get; set; }
        public virtual TiposWO TiposWO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WOPlanificadas> WOPlanificadas { get; set; }
    }
}
