//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zonas
    {
        public long IdObj { get; set; }
        public Nullable<int> FK_LINEAS_ID { get; set; }
        public string ZONA { get; set; }
        public string DESC_ZONA { get; set; }
        public Nullable<int> ORDEN_ZONA { get; set; }
        public string COMPARTIDA { get; set; }
        public string ID_ZONA { get; set; }
        public Nullable<short> ARRANQUE { get; set; }
        public Nullable<short> INICIO_CAMBIO_FIN { get; set; }
        public Nullable<short> INICIO_PAUSA { get; set; }
        public Nullable<short> PRODUCCION_COMPARTIDA { get; set; }
        public string ORDER_ID { get; set; }
        public string ORDER_ID_ANTERIOR { get; set; }
        public Nullable<short> PERMITE_PRODUCCION { get; set; }
        public Nullable<short> FLAG_CHECK_CONSOLIDADOS { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMA_ACTUALIZACION { get; set; }
        public Nullable<short> MAQUINAS_COMPARTIDAS { get; set; }
    }
}
