//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Alt
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentTypes
    {
        public DepartmentTypes()
        {
            this.TemplatesForms = new HashSet<TemplatesForms>();
            this.TemplatesLocations = new HashSet<TemplatesLocations>();
            this.TemplatesTriggers = new HashSet<TemplatesTriggers>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<TemplatesForms> TemplatesForms { get; set; }
        public virtual ICollection<TemplatesLocations> TemplatesLocations { get; set; }
        public virtual ICollection<TemplatesTriggers> TemplatesTriggers { get; set; }
    }
}
