//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Alt
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsMESData
    {
        public int ID { get; set; }
        public int idForm { get; set; }
        public string orderId { get; set; }
        public string orderTypeId { get; set; }
        public string turnoId { get; set; }
        public string shcId { get; set; }
        public string lotId { get; set; }
        public string materialId { get; set; }
        public string location { get; set; }
    
        public virtual Forms Forms { get; set; }
    }
}
