//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Alt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forms
    {
        public Forms()
        {
            this.FormsLog = new HashSet<FormsLog>();
            this.FormsMESData = new HashSet<FormsMESData>();
            this.StorageFiles = new HashSet<StorageFiles>();
        }
    
        public int ID { get; set; }
        public int idLocation { get; set; }
        public Nullable<int> idTrigger { get; set; }
        public Nullable<int> idSITinfo { get; set; }
        public string triggerName { get; set; }
        public string name { get; set; }
        public string descript { get; set; }
        public string statusID { get; set; }
        public Nullable<System.DateTime> createdOnUTC { get; set; }
        public Nullable<System.DateTime> lastModifyUTC { get; set; }
        public bool delete { get; set; }
        public Nullable<int> idInbox { get; set; }
        public int isValid { get; set; }
        public string errors { get; set; }
        public Nullable<int> idFormTemplate { get; set; }
        public string FormTemplate { get; set; }
        public string FormTemplateXML { get; set; }
        public string FormValues { get; set; }
        public string FormValuesXML { get; set; }
        public string path { get; set; }
    
        public virtual inboxTrigger inboxTrigger { get; set; }
        public virtual Status Status { get; set; }
        public virtual TemplatesLocations TemplatesLocations { get; set; }
        public virtual ICollection<FormsLog> FormsLog { get; set; }
        public virtual ICollection<FormsMESData> FormsMESData { get; set; }
        public virtual ICollection<StorageFiles> StorageFiles { get; set; }
    }
}
