//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Alt
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsLog
    {
        public int ID { get; set; }
        public int idForm { get; set; }
        public System.DateTime createdOn { get; set; }
        public string type { get; set; }
        public string traza { get; set; }
        public string usuario { get; set; }
    
        public virtual Forms Forms { get; set; }
    }
}
