//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Alt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FormsDBEnt : DbContext
    {
        public FormsDBEnt()
            : base("name=FormsDBEnt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FormsLog> FormsLog { get; set; }
        public DbSet<FormsMESData> FormsMESData { get; set; }
        public DbSet<inboxTrigger> inboxTrigger { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TemplatesFormsTypes> TemplatesFormsTypes { get; set; }
        public DbSet<TemplatesLocForms> TemplatesLocForms { get; set; }
        public DbSet<SIT_Locations> SIT_Locations { get; set; }
        public DbSet<SIT_Lots> SIT_Lots { get; set; }
        public DbSet<SIT_Materiales> SIT_Materiales { get; set; }
        public DbSet<SIT_Orders> SIT_Orders { get; set; }
        public DbSet<SIT_Orders_Types> SIT_Orders_Types { get; set; }
        public DbSet<SIT_SHC_Turnos> SIT_SHC_Turnos { get; set; }
        public DbSet<vTemplatesLocForms> vTemplatesLocForms { get; set; }
        public DbSet<vTemplatesLocFormTri> vTemplatesLocFormTri { get; set; }
        public DbSet<SIT_TiposTurno> SIT_TiposTurno { get; set; }
        public DbSet<SIT_Orders_Status> SIT_Orders_Status { get; set; }
        public DbSet<SIT_RTDS_Points> SIT_RTDS_Points { get; set; }
        public DbSet<TemplatesTriggersPlannedMonthNumDayTypes> TemplatesTriggersPlannedMonthNumDayTypes { get; set; }
        public DbSet<TemplatesTriggersPlannedTypes> TemplatesTriggersPlannedTypes { get; set; }
        public DbSet<TemplatesTriggersTypes> TemplatesTriggersTypes { get; set; }
        public DbSet<DepartmentTypes> DepartmentTypes { get; set; }
        public DbSet<TemplatesForms> TemplatesForms { get; set; }
        public DbSet<TemplatesLocations> TemplatesLocations { get; set; }
        public DbSet<TemplatesTriggers> TemplatesTriggers { get; set; }
        public DbSet<Forms> Forms { get; set; }
        public DbSet<StorageFiles> StorageFiles { get; set; }
        public DbSet<SIT_Orders_Status_Arranques_Cambios> SIT_Orders_Status_Arranques_Cambios { get; set; }
        public DbSet<TiposUnidades> TiposUnidades { get; set; }
        public DbSet<O2_Llenadoras> O2_Llenadoras { get; set; }
        public DbSet<O2_Llenadoras_Tolerancias> O2_Llenadoras_Tolerancias { get; set; }
        public DbSet<O2_Llenadoras_Parametros> O2_Llenadoras_Parametros { get; set; }
        public DbSet<O2_Llenadoras_ToleranciasCO2> O2_Llenadoras_ToleranciasCO2 { get; set; }
        public DbSet<Forms5sLibreSecciones> Forms5sLibreSecciones { get; set; }
    
        public virtual int checkTriggerCiclico()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("checkTriggerCiclico");
        }
    
        public virtual int checkTriggerOrders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("checkTriggerOrders");
        }
    
        public virtual int checkTriggerPlan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("checkTriggerPlan");
        }
    
        public virtual int checkTriggerTurno()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("checkTriggerTurno");
        }
    
        public virtual int copyTemplateForm(Nullable<int> idTemplateForm)
        {
            var idTemplateFormParameter = idTemplateForm.HasValue ?
                new ObjectParameter("idTemplateForm", idTemplateForm) :
                new ObjectParameter("idTemplateForm", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("copyTemplateForm", idTemplateFormParameter);
        }
    
        public virtual int checkTriggerPlanDaily()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("checkTriggerPlanDaily");
        }
    
        public virtual int checkTriggerPlanDailyCycle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("checkTriggerPlanDailyCycle");
        }
    
        public virtual int checkTriggerPlanMonthly()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("checkTriggerPlanMonthly");
        }
    
        public virtual int checkTriggerPlanMonthlyTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("checkTriggerPlanMonthlyTypes");
        }
    
        public virtual int checkTriggerPlanOnce()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("checkTriggerPlanOnce");
        }
    
        public virtual int checkTriggerPlanWeekly()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("checkTriggerPlanWeekly");
        }
    
        public virtual int checkTriggerPlanWeeklyCycle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("checkTriggerPlanWeeklyCycle");
        }
    
        public virtual int createFormFileRelation(Nullable<int> idForm, Nullable<int> idFile)
        {
            var idFormParameter = idForm.HasValue ?
                new ObjectParameter("idForm", idForm) :
                new ObjectParameter("idForm", typeof(int));
    
            var idFileParameter = idFile.HasValue ?
                new ObjectParameter("idFile", idFile) :
                new ObjectParameter("idFile", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createFormFileRelation", idFormParameter, idFileParameter);
        }
    
        public virtual int createTemplateFileRelation(Nullable<int> idTemForm, Nullable<int> idFile)
        {
            var idTemFormParameter = idTemForm.HasValue ?
                new ObjectParameter("idTemForm", idTemForm) :
                new ObjectParameter("idTemForm", typeof(int));
    
            var idFileParameter = idFile.HasValue ?
                new ObjectParameter("idFile", idFile) :
                new ObjectParameter("idFile", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createTemplateFileRelation", idTemFormParameter, idFileParameter);
        }
    }
}
