//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Alt
{
    using System;
    using System.Collections.Generic;
    
    public partial class inboxTrigger
    {
        public inboxTrigger()
        {
            this.Forms = new HashSet<Forms>();
        }
    
        public int ID { get; set; }
        public Nullable<int> idTrigger { get; set; }
        public Nullable<System.DateTime> createdOnUTC { get; set; }
        public string name { get; set; }
        public string typeID { get; set; }
        public string attr01 { get; set; }
        public string attr02 { get; set; }
        public string location { get; set; }
        public string orderId { get; set; }
        public string orderTypeId { get; set; }
        public string orderStatus { get; set; }
        public string orderStatusAnt { get; set; }
        public string turnoId { get; set; }
        public string shcId { get; set; }
        public string lotId { get; set; }
        public string materialId { get; set; }
        public Nullable<int> soloLocationID { get; set; }
        public string newDescript { get; set; }
        public Nullable<int> attrPlannedShiftActive { get; set; }
        public Nullable<int> attrPlannedOrderActive { get; set; }
        public Nullable<int> attrPlannedType { get; set; }
        public Nullable<System.DateTime> attrPlannedOnce { get; set; }
        public Nullable<int> attrPlannedDays { get; set; }
        public Nullable<int> attrPlannedWeeks { get; set; }
        public string attrPlannedWeekDays { get; set; }
        public Nullable<int> attrPlannedMonthIsHourly { get; set; }
        public Nullable<int> attrPlannedMonthDay { get; set; }
        public Nullable<int> attrPlannedMonthFrec { get; set; }
        public Nullable<int> attrPlannedMonthNumDay { get; set; }
        public string attrPlannedMonthDayWeek { get; set; }
        public Nullable<int> attrFrecuencyIsCycle { get; set; }
        public Nullable<System.TimeSpan> attrFrecuencyHour { get; set; }
        public Nullable<int> attrFrecuencyQuantity { get; set; }
        public Nullable<int> attrFrecuencyUnits { get; set; }
        public Nullable<System.TimeSpan> attrFrecuencyFrom { get; set; }
        public Nullable<System.TimeSpan> attrFrecuencyTo { get; set; }
    
        public virtual ICollection<Forms> Forms { get; set; }
    }
}
