//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Alt
{
    using System;
    using System.Collections.Generic;
    
    public partial class O2_Llenadoras
    {
        public long Id { get; set; }
        public string IdLinea { get; set; }
        public string Linea { get; set; }
        public int VolumenEnvase { get; set; }
        public byte Llenadora { get; set; }
        public string IdMuestra { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Comentario { get; set; }
        public short TCP { get; set; }
        public decimal O2_TCP { get; set; }
        public decimal CO2_TCP { get; set; }
        public string TipoMuestra { get; set; }
        public byte NumGrifo { get; set; }
        public decimal TPO { get; set; }
        public string UnidadTPO { get; set; }
        public decimal HSO { get; set; }
        public string UnidadHSO { get; set; }
        public decimal DO { get; set; }
        public string UnidadDO { get; set; }
        public decimal CO2 { get; set; }
        public string UnidadCO2 { get; set; }
        public decimal CO2_Ts { get; set; }
        public string UnidadCO2_Ts { get; set; }
        public decimal HSV { get; set; }
        public string UnidadHSV { get; set; }
        public decimal Presion { get; set; }
        public string UnidadPresion { get; set; }
        public decimal Temperatura { get; set; }
        public string UnidadTemperatura { get; set; }
        public decimal Temperatura_Ts { get; set; }
        public string UnidadTemperatura_Ts { get; set; }
        public string Fichero { get; set; }
        public decimal PresionVacio { get; set; }
        public string UnidadPresionVacio { get; set; }
        public decimal PresionEspumado { get; set; }
        public string UnidadPresionEspumado { get; set; }
        public decimal PresionSoplado { get; set; }
        public string UnidadPresionSoplado { get; set; }
        public decimal ConsumoGas { get; set; }
        public string UnidadConsumoGas { get; set; }
    }
}
