//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Alt
{
    using System;
    using System.Collections.Generic;
    
    public partial class O2_Llenadoras_ToleranciasCO2
    {
        public int Id { get; set; }
        public string Linea { get; set; }
        public decimal LimiteInferior { get; set; }
        public decimal LimiteSuperior { get; set; }
        public decimal ToleranciaInferior { get; set; }
        public decimal ToleranciaSuperior { get; set; }
    }
}
