//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Alt
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIT_Locations
    {
        public int LocPK { get; set; }
        public string LocID { get; set; }
        public string LocAlias { get; set; }
        public Nullable<int> ParentLocPK { get; set; }
        public Nullable<int> CommonLocPK { get; set; }
        public string LocPath { get; set; }
    }
}
