//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Alt
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIT_Orders
    {
        public string Id { get; set; }
        public string typeID { get; set; }
        public string IdProducto { get; set; }
        public string EstadoAct { get; set; }
        public string EstadoAnt { get; set; }
        public string EquipoOrden { get; set; }
        public System.DateTime FecHorAct { get; set; }
    }
}
