//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Alt
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIT_Lots
    {
        public int LotPK { get; set; }
        public string LotID { get; set; }
        public string LotName { get; set; }
        public int DefVerPK { get; set; }
        public Nullable<int> BomAltPK { get; set; }
        public Nullable<int> MasterLotPK { get; set; }
        public Nullable<int> ParentLotPK { get; set; }
        public string Descript { get; set; }
        public Nullable<decimal> InitQuantity { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public int UomPK { get; set; }
        public int LocPK { get; set; }
        public int LotStatusPK { get; set; }
        public Nullable<int> HutPK { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTill { get; set; }
        public Nullable<int> SourceLotPK { get; set; }
        public Nullable<int> TargetLotPK { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int LastUser { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public byte[] LocalInfo { get; set; }
        public string ContextID { get; set; }
        public System.Guid RowGuid { get; set; }
        public byte[] RowVer { get; set; }
        public bool RowDeleted { get; set; }
        public System.DateTime RowUpdated { get; set; }
    }
}
