//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Alt
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatesFormsTypes
    {
        public TemplatesFormsTypes()
        {
            this.TemplatesForms = new HashSet<TemplatesForms>();
        }
    
        public string typeID { get; set; }
    
        public virtual ICollection<TemplatesForms> TemplatesForms { get; set; }
    }
}
