//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Alt
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatesForms
    {
        public TemplatesForms()
        {
            this.TemplatesLocForms = new HashSet<TemplatesLocForms>();
            this.StorageFiles = new HashSet<StorageFiles>();
        }
    
        public int ID { get; set; }
        public int idDepartmentType { get; set; }
        public string name { get; set; }
        public string descript { get; set; }
        public Nullable<System.DateTime> createdOnUTC { get; set; }
        public Nullable<System.DateTime> lastModifyUTC { get; set; }
        public string typeID { get; set; }
        public string jsonTemplate { get; set; }
        public string xmlTemplate { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual DepartmentTypes DepartmentTypes { get; set; }
        public virtual ICollection<TemplatesLocForms> TemplatesLocForms { get; set; }
        public virtual TemplatesFormsTypes TemplatesFormsTypes { get; set; }
        public virtual ICollection<StorageFiles> StorageFiles { get; set; }
    }
}
