//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Alt
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatesTriggers
    {
        public TemplatesTriggers()
        {
            this.TemplatesLocForms = new HashSet<TemplatesLocForms>();
        }
    
        public int ID { get; set; }
        public int idDepartmentType { get; set; }
        public int status { get; set; }
        public string name { get; set; }
        public string descript { get; set; }
        public Nullable<System.DateTime> createdOnUTC { get; set; }
        public Nullable<System.DateTime> lastModifyUTC { get; set; }
        public string typeID { get; set; }
        public string locID { get; set; }
        public string attr01 { get; set; }
        public string attr02 { get; set; }
        public Nullable<int> attrPlannedShiftActive { get; set; }
        public Nullable<int> attrPlannedOrderActive { get; set; }
        public Nullable<int> attrPlannedType { get; set; }
        public Nullable<System.DateTime> attrPlannedOnce { get; set; }
        public Nullable<int> attrPlannedDays { get; set; }
        public Nullable<int> attrPlannedWeeks { get; set; }
        public string attrPlannedWeekDays { get; set; }
        public Nullable<int> attrPlannedMonthIsHourly { get; set; }
        public Nullable<int> attrPlannedMonthDay { get; set; }
        public Nullable<int> attrPlannedMonthFrec { get; set; }
        public Nullable<int> attrPlannedMonthNumDay { get; set; }
        public string attrPlannedMonthDayWeek { get; set; }
        public Nullable<int> attrFrecuencyIsCycle { get; set; }
        public Nullable<System.TimeSpan> attrFrecuencyHour { get; set; }
        public Nullable<int> attrFrecuencyQuantity { get; set; }
        public Nullable<int> attrFrecuencyUnits { get; set; }
        public Nullable<System.TimeSpan> attrFrecuencyFrom { get; set; }
        public Nullable<System.TimeSpan> attrFrecuencyTo { get; set; }
        public Nullable<int> attrValidHasUntil { get; set; }
        public Nullable<System.DateTime> attrValidFrom { get; set; }
        public Nullable<System.DateTime> attrValidUntil { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual DepartmentTypes DepartmentTypes { get; set; }
        public virtual TemplatesTriggersPlannedMonthNumDayTypes TemplatesTriggersPlannedMonthNumDayTypes { get; set; }
        public virtual TemplatesTriggersPlannedTypes TemplatesTriggersPlannedTypes { get; set; }
        public virtual TemplatesTriggersTypes TemplatesTriggersTypes { get; set; }
        public virtual ICollection<TemplatesLocForms> TemplatesLocForms { get; set; }
    }
}
