//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Alt
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatesTriggersTypes
    {
        public TemplatesTriggersTypes()
        {
            this.TemplatesTriggers = new HashSet<TemplatesTriggers>();
        }
    
        public string typeID { get; set; }
    
        public virtual ICollection<TemplatesTriggers> TemplatesTriggers { get; set; }
    }
}
