//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.BBDD.Alt
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatesLocations
    {
        public TemplatesLocations()
        {
            this.TemplatesLocForms = new HashSet<TemplatesLocForms>();
            this.TemplatesLocations1 = new HashSet<TemplatesLocations>();
            this.Forms = new HashSet<Forms>();
        }
    
        public int ID { get; set; }
        public int idDepartmentType { get; set; }
        public string shortName { get; set; }
        public string name { get; set; }
        public string descript { get; set; }
        public Nullable<int> idParent { get; set; }
        public Nullable<bool> idSITInherit { get; set; }
        public string idSITLoc { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> createdOnUTC { get; set; }
        public Nullable<System.DateTime> lastUpdatedUTC { get; set; }
    
        public virtual DepartmentTypes DepartmentTypes { get; set; }
        public virtual ICollection<TemplatesLocForms> TemplatesLocForms { get; set; }
        public virtual ICollection<TemplatesLocations> TemplatesLocations1 { get; set; }
        public virtual TemplatesLocations TemplatesLocations2 { get; set; }
        public virtual ICollection<Forms> Forms { get; set; }
    }
}
