//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SitMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SitMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSM.Resources.SitMessages", typeof(SitMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad a pedir Tanque = %ORD% fue %QTY% y no fue en el formato correcto, el mensaje no fue enviado a INFOR.
        /// </summary>
        internal static string _1000005 {
            get {
                return ResourceManager.GetString("-1000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SABPPAKOP.insertKOPValue returned false for KopCode=%kopName%, equipFullPath=%tankFullPath%, value=%kopValue%.
        /// </summary>
        internal static string _1000108 {
            get {
                return ResourceManager.GetString("-1000108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha no podía ponerse para KopCode=%kopName%, equipFullPath=%tankFullPath%, value=%kopValue%.
        /// </summary>
        internal static string _1000110 {
            get {
                return ResourceManager.GetString("-1000110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedades para el indicador de configuración de fecha de entrega (DuedateUpdTFM) no se han encontrado para el Orden = %ORD%.
        /// </summary>
        internal static string _1000202 {
            get {
                return ResourceManager.GetString("-1000202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado procedimiento para procesar el Orden %ORD%,no mensaje se ha enviado to INFOR.
        /// </summary>
        internal static string _1000301 {
            get {
                return ResourceManager.GetString("-1000301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo un procedimiento se ha esperado para procesar el Orden %ORD% pero se han encontrado más de uno, no mensaje se ha enviado a INFOR.
        /// </summary>
        internal static string _1000302 {
            get {
                return ResourceManager.GetString("-1000302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipo, Orden y procedimiento no estaban disponibles. No mensaje se ha enviado a INFOR.
        /// </summary>
        internal static string _1000500 {
            get {
                return ResourceManager.GetString("-1000500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción para manejar el Tanque (KOP-Status, etc.) para el Orden = %ORD_ID%, Procedimiento = %ENTRY%, KOP = %KOP%, Equipo = %EQUIP%. Excepción fue: %EX%.
        /// </summary>
        internal static string _1000503 {
            get {
                return ResourceManager.GetString("-1000503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipos, Orden y Procedimientos no disponible. No se puede completar.
        /// </summary>
        internal static string _1000504 {
            get {
                return ResourceManager.GetString("-1000504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pude recuperar Orden de ejecución y procedimiento del equipo. Por favor Pruba que le Orden esta en ejecución. No mensaje se ha enviado a INFOR..
        /// </summary>
        internal static string _1000505 {
            get {
                return ResourceManager.GetString("-1000505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallo de la actualización de la cantidad del Tanque para el tanque = %LOT_EQUIPMENT% porque no se ha encontrado el Tanque dentro del MM..
        /// </summary>
        internal static string _1000515 {
            get {
                return ResourceManager.GetString("-1000515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallo de la actualización de la cantidad del Tanque para el tanque = %LOT_EQUIPMENT% con la Excepción = %EXCEPTION%.
        /// </summary>
        internal static string _1000517 {
            get {
                return ResourceManager.GetString("-1000517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de la orden no encontrados para Tanque.
        /// </summary>
        internal static string _1000540 {
            get {
                return ResourceManager.GetString("-1000540", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudó enviar el mensaje de caracteristicas de lote a SAP para el Orden %ORDER%, Error del PM = %ERR%, Error-desc. = %ERRDSC%.
        /// </summary>
        internal static string _10005401 {
            get {
                return ResourceManager.GetString("-10005401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudó recuperar el orden de ejecución y el procedimeinto del tanque. Por favor verifica que un orden esta en ejecución para el tanque..
        /// </summary>
        internal static string _1000542 {
            get {
                return ResourceManager.GetString("-1000542", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudó recuperar el orden de ejecución y el procedimeinto del tanque. Por favor verifica que un orden esta en ejecución para el tanque..
        /// </summary>
        internal static string _1000543 {
            get {
                return ResourceManager.GetString("-1000543", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: El mensaje no se ha enviado a INFOR..
        /// </summary>
        internal static string _1000544 {
            get {
                return ResourceManager.GetString("-1000544", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No datos encontrado para el Orden = %ORD%, No se ha enviado mensaje a INFOR.
        /// </summary>
        internal static string _1000602 {
            get {
                return ResourceManager.GetString("-1000602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado una entrada de primer nivel para el Orden = %ORD%, No mensaje se ha enviado a INFOR.
        /// </summary>
        internal static string _1000603 {
            get {
                return ResourceManager.GetString("-1000603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO se ha encontrado datos de procedimiento (Sub-Entrada) para el orden = %ORD%, Procedimiento = %SUB_ENTRY%, NO mensaje se ha enviado a INFOR.
        /// </summary>
        internal static string _1000604 {
            get {
                return ResourceManager.GetString("-1000604", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha enontrado datos de equipo para el Orden = %ORD%, Procedimiento = %SUB_ENTRY%, Equipo =%EQUIP%, No mensaje se ha enviado a INFOR.
        /// </summary>
        internal static string _1000606 {
            get {
                return ResourceManager.GetString("-1000606", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcohol para el Orden = %ORD%, Procedimiento = %SUB_ENTRY% fue %ALCOHOL% y no fue en el formato correcto, no mensaje se ha enviado a INFOR.
        /// </summary>
        internal static string _1000607 {
            get {
                return ResourceManager.GetString("-1000607", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin del flujo de salida del Orden = %ORD%, Procedimiento = %SUB_ENTRY% fue %DATE% y no fue en el formato correcto, No se ha enviado mensaje a INFOR.
        /// </summary>
        internal static string _1000608 {
            get {
                return ResourceManager.GetString("-1000608", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio del flujo de salida del Orden = %ORD%, Procedimiento = %SUB_ENTRY% fue %DATE% y no fue en el formato correcto, no se ha enviado mensaje a INFOR.
        /// </summary>
        internal static string _1000609 {
            get {
                return ResourceManager.GetString("-1000609", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##_End Inflow of Order = %ORD%, Procedure = %SUB_ENTRY% was %DATE% and was not in the correct format, Message was not sent to INFOR.
        /// </summary>
        internal static string _1000610 {
            get {
                return ResourceManager.GetString("-1000610", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lote vacio.
        /// </summary>
        internal static string _123 {
            get {
                return ResourceManager.GetString("-123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lote ya utilizado.
        /// </summary>
        internal static string _124 {
            get {
                return ResourceManager.GetString("-124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen más órdenes en ejecución en el destino.
        /// </summary>
        internal static string _125 {
            get {
                return ResourceManager.GetString("-125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden seleccionada es una orden simulada.
        /// </summary>
        internal static string _126 {
            get {
                return ResourceManager.GetString("-126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos de extracto de las características del lote están vacíos.
        /// </summary>
        internal static string _127 {
            get {
                return ResourceManager.GetString("-127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay demasiado ordenes en ejecución (#%orderCount%) en la celda %cellId%.
        /// </summary>
        internal static string _128 {
            get {
                return ResourceManager.GetString("-128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un procedimiento en ejecución en el equipo.
        /// </summary>
        internal static string _129 {
            get {
                return ResourceManager.GetString("-129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor complete todo los procedimientos.
        /// </summary>
        internal static string _130 {
            get {
                return ResourceManager.GetString("-130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad producida es nula.
        /// </summary>
        internal static string _132 {
            get {
                return ResourceManager.GetString("-132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay demasiado ordenes en ejecución (%orderList%).
        /// </summary>
        internal static string _133 {
            get {
                return ResourceManager.GetString("-133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIS error enviando un mensaje (%disMessageId%).
        /// </summary>
        internal static string _134 {
            get {
                return ResourceManager.GetString("-134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antes de producir, hay que declarar un consumo.
        /// </summary>
        internal static string _135 {
            get {
                return ResourceManager.GetString("-135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen caracterisiticas de lote vacias  (%list%).
        /// </summary>
        internal static string _136 {
            get {
                return ResourceManager.GetString("-136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %kopName% falta.
        /// </summary>
        internal static string _137 {
            get {
                return ResourceManager.GetString("-137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe ordenes (%orderList%) en ejecución en el equipo seleccionado (%equipId%).
        /// </summary>
        internal static string _138 {
            get {
                return ResourceManager.GetString("-138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallo en la conversión de Unidad de Medida (UoM) (%uomSource% -&gt; %uomDest%).
        /// </summary>
        internal static string _139 {
            get {
                return ResourceManager.GetString("-139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible de alinear el tanque fuente %TANK-ID% con el material %MAT-ID%.
        /// </summary>
        internal static string _140 {
            get {
                return ResourceManager.GetString("-140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sistema %ID%.
        /// </summary>
        internal static string _141 {
            get {
                return ResourceManager.GetString("-141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe otro material (%materialId%) en el destino (%equipId%).
        /// </summary>
        internal static string _142 {
            get {
                return ResourceManager.GetString("-142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El orden ya es arrancado. Por favor pincha Refrescar.
        /// </summary>
        internal static string _143 {
            get {
                return ResourceManager.GetString("-143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay demasiado ordenes en ejecución (%orderList%) en el equipo fuente (%sourceEquip%).
        /// </summary>
        internal static string _144 {
            get {
                return ResourceManager.GetString("-144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay demasiado ordenes en ejecución (%orderList%) en el equipo destino (%sourceEquip%).
        /// </summary>
        internal static string _145 {
            get {
                return ResourceManager.GetString("-145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error intentando de guardar el ID del filtro de ejecución de orden en el orden: %OrderID%. %Message%.
        /// </summary>
        internal static string _220 {
            get {
                return ResourceManager.GetString("-220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede abrir de nuevo un orden cerrado desde más de %days% días..
        /// </summary>
        internal static string CannotReopenOrder {
            get {
                return ResourceManager.GetString("CannotReopenOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede que el tiempo de fin sea despues del inicio del orden y antes de ahora..
        /// </summary>
        internal static string checkCompleteDate {
            get {
                return ResourceManager.GetString("checkCompleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algunas declaración de producción tienen una fecha/hora más elevada que la fecha/hora insertada..
        /// </summary>
        internal static string checkCompleteDateLessThenDeclarations {
            get {
                return ResourceManager.GetString("checkCompleteDateLessThenDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted quiere sobrescribir %kopList% con el nuevo tiempo de fin ?.
        /// </summary>
        internal static string CompleteProcedureEndTimeOverwrite {
            get {
                return ResourceManager.GetString("CompleteProcedureEndTimeOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El procedimiento de flujo inverso se ha terminado con una error. Verifica si existe algunos problemas con el consumo de material..
        /// </summary>
        internal static string ErrorInBackflushProcedure {
            get {
                return ResourceManager.GetString("ErrorInBackflushProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden ya confirmado. Por favor pincha Refrescar.
        /// </summary>
        internal static string OrderAlreadyConfirmed {
            get {
                return ResourceManager.GetString("OrderAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación no autorizada. Orden consumido (%orderId%) no esta en ejecución.
        /// </summary>
        internal static string ReverseDestOrderIsNotRunning {
            get {
                return ResourceManager.GetString("ReverseDestOrderIsNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen varios errores de flujo inverso relativas con la declaración de producción seleccionada, por favor resuelvelas y intenta de nuevo..
        /// </summary>
        internal static string ReverseMaterialIsBackFlushedWithError {
            get {
                return ResourceManager.GetString("ReverseMaterialIsBackFlushedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO se ha hecho la operación de flujo inverso en la declaración de producción seleccionada, por favor intenta de nuevo más tarde..
        /// </summary>
        internal static string ReverseMaterialIsNotYetBackFlushed {
            get {
                return ResourceManager.GetString("ReverseMaterialIsNotYetBackFlushed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallo en la conexión con el serve de OEE.
        /// </summary>
        internal static string SAB_OEE_BADCONNECTION {
            get {
                return ResourceManager.GetString("SAB_OEE_BADCONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error desconocida.
        /// </summary>
        internal static string SAB_OEE_ERROR {
            get {
                return ResourceManager.GetString("SAB_OEE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación fallada.
        /// </summary>
        internal static string SAB_OEE_FAIL {
            get {
                return ResourceManager.GetString("SAB_OEE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato dentro del periodo congelado.
        /// </summary>
        internal static string SAB_OEE_FROZEN_PERIOD {
            get {
                return ResourceManager.GetString("SAB_OEE_FROZEN_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gama de tiempo no válida.
        /// </summary>
        internal static string SAB_OEE_INVALID_TIME_RANGE {
            get {
                return ResourceManager.GetString("SAB_OEE_INVALID_TIME_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gama de valores no válida.
        /// </summary>
        internal static string SAB_OEE_INVALID_VALUE_RANGE {
            get {
                return ResourceManager.GetString("SAB_OEE_INVALID_VALUE_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perametros no válidos.
        /// </summary>
        internal static string SAB_OEE_INVALIDARG {
            get {
                return ResourceManager.GetString("SAB_OEE_INVALIDARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración no válida.
        /// </summary>
        internal static string SAB_OEE_INVALIDCONFIG {
            get {
                return ResourceManager.GetString("SAB_OEE_INVALIDCONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos no válidos.
        /// </summary>
        internal static string SAB_OEE_INVALIDDATA {
            get {
                return ResourceManager.GetString("SAB_OEE_INVALIDDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación no válida.
        /// </summary>
        internal static string SAB_OEE_INVALIDOPERATION {
            get {
                return ResourceManager.GetString("SAB_OEE_INVALIDOPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación timeout.
        /// </summary>
        internal static string SAB_OEE_TIMEOUT {
            get {
                return ResourceManager.GetString("SAB_OEE_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden %orderId% abortado con éxito.
        /// </summary>
        internal static string SABAbortOrderOK {
            get {
                return ResourceManager.GetString("SABAbortOrderOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe otro lote (%batchId%) en el tanque de destino (%sloc%).
        /// </summary>
        internal static string SABAnotherBatchForFL {
            get {
                return ResourceManager.GetString("SABAnotherBatchForFL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta seguro de abortar el orden ?.
        /// </summary>
        internal static string SABAskAbortOrder {
            get {
                return ResourceManager.GetString("SABAskAbortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta seguro de completar el orden ?.
        /// </summary>
        internal static string SABAskCompleteOrder {
            get {
                return ResourceManager.GetString("SABAskCompleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay órdenes en ejecución en este equipo. Quiere continuar ?.
        /// </summary>
        internal static string SABAskConfirmForTankStatusChangeNoOrder {
            get {
                return ResourceManager.GetString("SABAskConfirmForTankStatusChangeNoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay ordenes en ejecución en ests equipo. Quiere continuar ?.
        /// </summary>
        internal static string SABAskConfirmForTankStatusChangeOneOrder {
            get {
                return ResourceManager.GetString("SABAskConfirmForTankStatusChangeOneOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El equipo de ejecución no esta en el estado &quot;Disponible para transferencia&quot;. Quiere continuar ?.
        /// </summary>
        internal static string SABAvForTransferTankStatus {
            get {
                return ResourceManager.GetString("SABAvForTransferTankStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad en el Tanque (%tankName%) se reducirá del valor %declaredQty% HL - %OPFECROPDILUTIONVOL_Value% HL . Usted confirma ?.
        /// </summary>
        internal static string SABConfirmCropDilutionVol {
            get {
                return ResourceManager.GetString("SABConfirmCropDilutionVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad consumida es nula. ¿Está seguro de cerrar la orden ?.
        /// </summary>
        internal static string SABconsumedQuantityIsZero {
            get {
                return ResourceManager.GetString("SABconsumedQuantityIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, selecciona un countador primero.
        /// </summary>
        internal static string SABCountersUpdateNoCTRSelected {
            get {
                return ResourceManager.GetString("SABCountersUpdateNoCTRSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: fallo en la creación de filtro de ejecución.
        /// </summary>
        internal static string SABCreateFilterRunCreateFilterFailed {
            get {
                return ResourceManager.GetString("SABCreateFilterRunCreateFilterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: El tiempo de fin debería ser superior al tiempo de inicio.
        /// </summary>
        internal static string SABCreateOrderEndTimeGreaterStartTime {
            get {
                return ResourceManager.GetString("SABCreateOrderEndTimeGreaterStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: fallo en la creación desde plantilla.
        /// </summary>
        internal static string SABCreateOrderErrorCreationFromTemplate {
            get {
                return ResourceManager.GetString("SABCreateOrderErrorCreationFromTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: fallo poniendo las caracteristicas de &apos;Categoría&apos; !.
        /// </summary>
        internal static string SABCreateOrderFailureCategoryProperty {
            get {
                return ResourceManager.GetString("SABCreateOrderFailureCategoryProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: fallo poniendo las propiedades de &apos;Comentario&apos; !.
        /// </summary>
        internal static string SABCreateOrderFailureCommentProperty {
            get {
                return ResourceManager.GetString("SABCreateOrderFailureCommentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: fallo poniendo las propiedades de &apos;fecha de entrega&apos; !.
        /// </summary>
        internal static string SABCreateOrderFailureDueDateProperty {
            get {
                return ResourceManager.GetString("SABCreateOrderFailureDueDateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: fallo en la modificación de campos (FinalMaterialID,TypeID, ERPID,Estimated Start &amp; End time).
        /// </summary>
        internal static string SABCreateOrderFailureFieldsModification {
            get {
                return ResourceManager.GetString("SABCreateOrderFailureFieldsModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: fallo poniendo las propiedades de &apos;desde el tanque&apos; !.
        /// </summary>
        internal static string SABCreateOrderFailureFromTankProperty {
            get {
                return ResourceManager.GetString("SABCreateOrderFailureFromTankProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: fallo poniendo las propiedades de &apos;Orden liado&apos; !.
        /// </summary>
        internal static string SABCreateOrderFailureOrderLinkedProperty {
            get {
                return ResourceManager.GetString("SABCreateOrderFailureOrderLinkedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: fallo poniendo las propiedades de &apos;velocidad del flujo de salida&apos; !.
        /// </summary>
        internal static string SABCreateOrderFailureOutFlowDateProperty {
            get {
                return ResourceManager.GetString("SABCreateOrderFailureOutFlowDateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: fallo poniendo las propiedades de &apos;Recursos&apos; !.
        /// </summary>
        internal static string SABCreateOrderFailureResourceProperty {
            get {
                return ResourceManager.GetString("SABCreateOrderFailureResourceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: cantidad no válida.
        /// </summary>
        internal static string SABCreateOrderInvalidQty {
            get {
                return ResourceManager.GetString("SABCreateOrderInvalidQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: tiempo de inicio o de fin no válido.
        /// </summary>
        internal static string SABCreateOrderInvalidStartOrEndTime {
            get {
                return ResourceManager.GetString("SABCreateOrderInvalidStartOrEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: por favor rellena todos los campos obligatorios.
        /// </summary>
        internal static string SABCreateOrderRequiredFields {
            get {
                return ResourceManager.GetString("SABCreateOrderRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: no se ha encontrado la plantilla del orden !.
        /// </summary>
        internal static string SABCreateOrderTemplateNotFound {
            get {
                return ResourceManager.GetString("SABCreateOrderTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: fallo en la transición hasta el estado planificado !.
        /// </summary>
        internal static string SABCreateOrderTransitionFailed {
            get {
                return ResourceManager.GetString("SABCreateOrderTransitionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia la cantidad a 0 o confirma la cantidad dentro del tanque.
        /// </summary>
        internal static string SABEmptyCleanWarning {
            get {
                return ResourceManager.GetString("SABEmptyCleanWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato no válido.
        /// </summary>
        internal static string SABInvalidFormatCalendar {
            get {
                return ResourceManager.GetString("SABInvalidFormatCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, seleccione primero el equipo (*).
        /// </summary>
        internal static string SABInventoryManagementMandatorySourceEquipment {
            get {
                return ResourceManager.GetString("SABInventoryManagementMandatorySourceEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado un ID externo para el equipo.
        /// </summary>
        internal static string SABInventoryManagementNOExternalIdFound {
            get {
                return ResourceManager.GetString("SABInventoryManagementNOExternalIdFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;BR/&gt;No se ha encontrado ID externo para el equipo.
        /// </summary>
        internal static string SABInventoryManagementNOExternalIdFoundWithBR {
            get {
                return ResourceManager.GetString("SABInventoryManagementNOExternalIdFoundWithBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad debe ser &lt;= a la cantidad libre del equipo [%unrestrictedQty%] (*).
        /// </summary>
        internal static string SABInventoryManagementUnrestrictedQty {
            get {
                return ResourceManager.GetString("SABInventoryManagementUnrestrictedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOP %kopName% no actualizado.
        /// </summary>
        internal static string SABKopUpdateNotOK {
            get {
                return ResourceManager.GetString("SABKopUpdateNotOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOP %kopName% actualizado con éxito.
        /// </summary>
        internal static string SABKopUpdateOK {
            get {
                return ResourceManager.GetString("SABKopUpdateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tiempo seleccionado excede el máximo número de horas autorizado %max_time_range%.
        /// </summary>
        internal static string SABMaxTimeRangeWarning {
            get {
                return ResourceManager.GetString("SABMaxTimeRangeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay más procedimientos en ejecución en el equipo de destino. Si usted continúa, solo se va guardar los datos en el POM. ¿Quiere continuar?.
        /// </summary>
        internal static string SABMoreEntriesInDestinationEquipment {
            get {
                return ResourceManager.GetString("SABMoreEntriesInDestinationEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay más ordenes en ejecución en el equipo de destino. Por favor contacta su administrador de sistema..
        /// </summary>
        internal static string SABMoreOrdersInDestinationEquipment {
            get {
                return ResourceManager.GetString("SABMoreOrdersInDestinationEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay demasiadas órdenes en ejecución. ¿Desea continuar ?.
        /// </summary>
        internal static string SABMoreThenOneEntryInExecutionEquipment {
            get {
                return ResourceManager.GetString("SABMoreThenOneEntryInExecutionEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay multiples lotes en el tanque de destino (%sloc%)..
        /// </summary>
        internal static string SABMultipleBatchesForFL {
            get {
                return ResourceManager.GetString("SABMultipleBatchesForFL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden %newOrderId% creado con éxito.
        /// </summary>
        internal static string SABNewOrderOK {
            get {
                return ResourceManager.GetString("SABNewOrderOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación no se puede hacer porque la cantidad declarada es inferior al volumen de dilución.
        /// </summary>
        internal static string SABNotAllowCropDilutionVol {
            get {
                return ResourceManager.GetString("SABNotAllowCropDilutionVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El equipo de ejecución no esta en el estado &apos;vacío limpio&apos;. ¿Quiere continuar?.
        /// </summary>
        internal static string SABNotEmptyCleanTankStatus {
            get {
                return ResourceManager.GetString("SABNotEmptyCleanTankStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El equipo de ejecución (%execEquipment%) está en estado &apos;%status%&apos;  pero tiene que estar en %allowedStatus%. ¿Quiere continuar?.
        /// </summary>
        internal static string SABNotOkTankStatus {
            get {
                return ResourceManager.GetString("SABNotOkTankStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sello de tiempo no puede estar en el futuro.
        /// </summary>
        internal static string SABOEECounterFutureTimestampError {
            get {
                return ResourceManager.GetString("SABOEECounterFutureTimestampError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor selecciona el campo obligatorio ID Orden.
        /// </summary>
        internal static string SABOEECounterNoOrderSelected {
            get {
                return ResourceManager.GetString("SABOEECounterNoOrderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserta el campo obligatorio sello de tiempo.
        /// </summary>
        internal static string SABOEECounterNoTimestampError {
            get {
                return ResourceManager.GetString("SABOEECounterNoTimestampError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error procesando el countador: %processing_error%.
        /// </summary>
        internal static string SABOEECounterProcessingError {
            get {
                return ResourceManager.GetString("SABOEECounterProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad tiene que ser positiva.
        /// </summary>
        internal static string SABOEECounterValueInvalid {
            get {
                return ResourceManager.GetString("SABOEECounterValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error procesando daos: %processing_error%.
        /// </summary>
        internal static string SABOEEDataProcessingError {
            get {
                return ResourceManager.GetString("SABOEEDataProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación de escritura fallada (eliminar tiempo de paro) .
        /// </summary>
        internal static string SABOEEDTMErrorDelete {
            get {
                return ResourceManager.GetString("SABOEEDTMErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación de escritura fallada (fusionar tiempo de paro).
        /// </summary>
        internal static string SABOEEDTMErrorMerge {
            get {
                return ResourceManager.GetString("SABOEEDTMErrorMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación abortada: el periodo del  nuevo tiempo de paro afecta dos ordenes distintos.
        /// </summary>
        internal static string SABOEEDTMErrorMultiOrder {
            get {
                return ResourceManager.GetString("SABOEEDTMErrorMultiOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación de escritura fallada (dividir tiempo de paro).
        /// </summary>
        internal static string SABOEEDTMErrorSplit {
            get {
                return ResourceManager.GetString("SABOEEDTMErrorSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación de escritura fallada (actualizar tiempo de para).
        /// </summary>
        internal static string SABOEEDTMErrorUpdate {
            get {
                return ResourceManager.GetString("SABOEEDTMErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado tiempo de paro.
        /// </summary>
        internal static string SABOEEDTMNoRecordsFound {
            get {
                return ResourceManager.GetString("SABOEEDTMNoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor selecciona una línea.
        /// </summary>
        internal static string SABOEEManualInputSelectRow {
            get {
                return ResourceManager.GetString("SABOEEManualInputSelectRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted esta seguro de confirmar la operación de fusión por abajo ?.
        /// </summary>
        internal static string SABOEEMergeDownConfirm {
            get {
                return ResourceManager.GetString("SABOEEMergeDownConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted esta seguro de confirmar la operación de fusión por arriba ?.
        /// </summary>
        internal static string SABOEEMergeUpConfirm {
            get {
                return ResourceManager.GetString("SABOEEMergeUpConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No equipo seleccionado.
        /// </summary>
        internal static string SABOEENoEquipmentSelected {
            get {
                return ResourceManager.GetString("SABOEENoEquipmentSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tiempo de fin no puede estar en el futuro.
        /// </summary>
        internal static string SABOEENoFutureTime {
            get {
                return ResourceManager.GetString("SABOEENoFutureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserta el campo obligatorio del motivo.
        /// </summary>
        internal static string SABOEENoReasonSelected {
            get {
                return ResourceManager.GetString("SABOEENoReasonSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserta los valores obligatorios de tiempo.
        /// </summary>
        internal static string SABOEENoTimeSet {
            get {
                return ResourceManager.GetString("SABOEENoTimeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El sello de tiempo no puede ser inferior al último insertado.
        /// </summary>
        internal static string SABOEEQuantityTimestampError {
            get {
                return ResourceManager.GetString("SABOEEQuantityTimestampError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted esta seguro de confirmar la operación de actualización ?.
        /// </summary>
        internal static string SABOEEUpdateConfirm {
            get {
                return ResourceManager.GetString("SABOEEUpdateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor selecciona el tanque correcto de la lista (^).
        /// </summary>
        internal static string SABPlanningManagementSelectRealResource {
            get {
                return ResourceManager.GetString("SABPlanningManagementSelectRealResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación no está permitida porque la declaración de producción ya se ha hecho.
        /// </summary>
        internal static string SABProdDeclareAlreadyDone {
            get {
                return ResourceManager.GetString("SABProdDeclareAlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad producida no está en los + o - 10% de lo planificado. ¿Quiere completar la orden ?.
        /// </summary>
        internal static string SABproducedQuantityIsEnough {
            get {
                return ResourceManager.GetString("SABproducedQuantityIsEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La declaración final ya se ha hecho – otras declaraciones de produción fallarán en ERP.
        /// </summary>
        internal static string SABProductDeclareIsFinal {
            get {
                return ResourceManager.GetString("SABProductDeclareIsFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor rellene todos los campos obligatorios (*).
        /// </summary>
        internal static string SABRequiredFields {
            get {
                return ResourceManager.GetString("SABRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La interfase de lote y de stock no esta disponible (SAP Web service) .
        /// </summary>
        internal static string SABSapWebServiceError {
            get {
                return ResourceManager.GetString("SABSapWebServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la regla PLO_SPLIT_ORDER .
        /// </summary>
        internal static string SABSplitFormSplitOrderRuleError {
            get {
                return ResourceManager.GetString("SABSplitFormSplitOrderRuleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la regla PLO_TERMINATE_ORDER .
        /// </summary>
        internal static string SABSplitFormTerminateOrderRuleError {
            get {
                return ResourceManager.GetString("SABSplitFormTerminateOrderRuleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación completada con éxito.
        /// </summary>
        internal static string SABStandardSucces {
            get {
                return ResourceManager.GetString("SABStandardSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han encontrado TCPs compatibles. ¿Desea continuar ?.
        /// </summary>
        internal static string SABStartStepNoBBTRetrievedFromSAP {
            get {
                return ResourceManager.GetString("SABStartStepNoBBTRetrievedFromSAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la operación de actualización.
        /// </summary>
        internal static string SABStopJustificationFailedUpdate {
            get {
                return ResourceManager.GetString("SABStopJustificationFailedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combinar registros de dos órdenes diferentes no está permitido.
        /// </summary>
        internal static string SABStopJustificationMergeDifferentOrders {
            get {
                return ResourceManager.GetString("SABStopJustificationMergeDifferentOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la operación de combinación.
        /// </summary>
        internal static string SABStopJustificationMergeUpFailed {
            get {
                return ResourceManager.GetString("SABStopJustificationMergeUpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserte el campo obligatorio de tiempo de fin.
        /// </summary>
        internal static string SABStopJustificationNoEndTime {
            get {
                return ResourceManager.GetString("SABStopJustificationNoEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserte el campo obligatorio de tiempo de inicio.
        /// </summary>
        internal static string SABStopJustificationNoStartTime {
            get {
                return ResourceManager.GetString("SABStopJustificationNoStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividir.
        /// </summary>
        internal static string SABStopJustificationSplit {
            get {
                return ResourceManager.GetString("SABStopJustificationSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación abortada: %validation_error%.
        /// </summary>
        internal static string SABStopJustificationValidationFailed {
            get {
                return ResourceManager.GetString("SABStopJustificationValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tiempo de fin debe ser superior al tiempo de inicio.
        /// </summary>
        internal static string SABStopJustificationWrongTimes {
            get {
                return ResourceManager.GetString("SABStopJustificationWrongTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden %oDummy% sincronizada con éxito con la orden ERP %oReal% .
        /// </summary>
        internal static string SABSynchOrderOK {
            get {
                return ResourceManager.GetString("SABSynchOrderOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha límite vacía:&lt;BR/&gt; Puesta a mañana pero se puede modificar..
        /// </summary>
        internal static string SABTankChangeDueDateDefault {
            get {
                return ResourceManager.GetString("SABTankChangeDueDateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay entrada relacionada con este equipo:&lt;BR/&gt; no se puede asignar fecha límite..
        /// </summary>
        internal static string SABTankChangeDueDateNoEntries {
            get {
                return ResourceManager.GetString("SABTankChangeDueDateNoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha límite debe ser en el futuro..
        /// </summary>
        internal static string SABTankChangeDueDateWrongDate {
            get {
                return ResourceManager.GetString("SABTankChangeDueDateWrongDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la fecha y el equipo para obtener el turno relacionado.
        /// </summary>
        internal static string SABTeamManagementDateEquipmentMandatory {
            get {
                return ResourceManager.GetString("SABTeamManagementDateEquipmentMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado turno para la fecha y el equipo seleccionados..
        /// </summary>
        internal static string SABTeamManagementNoShiftFound {
            get {
                return ResourceManager.GetString("SABTeamManagementNoShiftFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la actualización del contador ha fallado..
        /// </summary>
        internal static string SABUpdateCountersUpdateFailed {
            get {
                return ResourceManager.GetString("SABUpdateCountersUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado turno para el año y la semana seleccionada: todos los datos cargados..
        /// </summary>
        internal static string SABWeekManagementNoShiftFound {
            get {
                return ResourceManager.GetString("SABWeekManagementNoShiftFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error enviando el mensaje al sistema de control..
        /// </summary>
        internal static string SendBacthMessageToShopFloor {
            get {
                return ResourceManager.GetString("SendBacthMessageToShopFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La orden %orderId% no se puede sincronizar más..
        /// </summary>
        internal static string SynchOrderNoMoreOkError {
            get {
                return ResourceManager.GetString("SynchOrderNoMoreOkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay errores no resueltos en el consumo de material. Por favor resuelva estos errores antes de cerrar la orden..
        /// </summary>
        internal static string UserMustFixErrorsAfterBackflush {
            get {
                return ResourceManager.GetString("UserMustFixErrorsAfterBackflush", resourceCulture);
            }
        }
    }
}
