USE [MES_MSM_Fabricacion]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [Fab].[vEstadoKOP_WO]
AS
	SELECT	WSP.IdWO, WOs.CodWO, 
			--MAX(CASE WHEN IdEstadoKOP = 1 THEN 1 ELSE 0 END) INEXISTENTE,
			--MAX(CASE WHEN IdEstadoKOP = 2 THEN 2 ELSE 0 END) MALO,
			--MAX(CASE WHEN IdEstadoKOP = 3 THEN 3 ELSE 0 END) BUENO
		CASE WHEN MAX(CASE WHEN IdEstadoKOP = 1 THEN 1 ELSE 0 END) = 1 THEN 1
			 WHEN MAX(CASE WHEN IdEstadoKOP = 1 THEN 1 ELSE 0 END) = 0 AND MAX(CASE WHEN IdEstadoKOP = 2 THEN 1 ELSE 0 END) = 1 THEN 2
			 ELSE 3 END AS IdEstadoKOP
	FROM	Fab.WOsKOPs as WOK
			INNER JOIN Fab.WOsSubProcesos as WSP ON WSP.IdWOSubProceso = WOK.IdWOSubProceso
			INNER JOIN Fab.WOs as WOs ON WOs.IdWO = WSP.IdWO
			INNER JOIN Fab.SubProcesos as SPS ON SPS.IdSubProceso = WSP.IdSubProceso
			INNER JOIN Fab.Procesos as PRO ON PRO.IdProceso = SPS.IdProceso
	GROUP BY WSP.IdWO, WOs.CodWO
GO


