Begin Try
	Use MES_MSM
	Declare @CompleteName nvarchar(max)
	Declare @SITTable nvarchar(max)
	Declare @SITType nvarchar(max)
	Declare @Query nvarchar(max) = N''
	Declare @Catalog nvarchar(max)

	--Delete Synonyms
	SELECT @Query += N'DROP SYNONYM ' + QUOTENAME(SCHEMA_NAME([schema_id])) + N'.' + QUOTENAME(name) + N';' + Char(13) + Char(10)
	FROM MES_MSM.sys.synonyms
	WHERE SCHEMA_NAME([schema_id]) = N'dbo'

	Exec MES_MSM.sys.sp_executesql @Query

	Declare c cursor for
		    select TABLE_CATALOG,TABLE_NAME CompleteName,SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1) SITTable,
			'COB_MSM_'+SUBSTRING(SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1),0,CHARINDEX('$',SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1))-1) SITType
			from SITMesDb.INFORMATION_SCHEMA.TABLES SIT
			left join MES_MSM.sys.synonyms MSM on SUBSTRING(SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1),0,CHARINDEX('$',SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1))-1) = MSM.name
			WHERE TABLE_CATALOG = 'sitMesDb' and TABLE_NAME like '%CURVAS%$'
			UNION ALL
			select TABLE_CATALOG,TABLE_NAME CompleteName,SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1) SITTable,
			SUBSTRING(SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1),0,CHARINDEX('$',SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1))-1) SITType
			from SITMesDb.INFORMATION_SCHEMA.TABLES SIT
			left join MES_MSM.sys.synonyms MSM on SUBSTRING(SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1),0,CHARINDEX('$',SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1))-1) = MSM.name
			WHERE TABLE_CATALOG = 'sitMesDb' and TABLE_NAME like '%COB%$'
			UNION ALL
			select TABLE_CATALOG,TABLE_NAME,SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1),
			SubString(SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1),0,CharIndex('_',SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1)))
			from LogBook.INFORMATION_SCHEMA.TABLES SIT
			where TABLE_NAME like '%ARCH_T_CSLIBLog/LogBook_%'
			UNION ALL
			select TABLE_CATALOG,TABLE_NAME,SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1),
			SubString(SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1),0,CharIndex('_',SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1)))
			from PPA.INFORMATION_SCHEMA.TABLES SIT
			where TABLE_NAME like 'T_OEEEng%OEEStateList_%'
			UNION ALL
			select TABLE_CATALOG,TABLE_NAME,SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1),
			SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1)
			from PPA.INFORMATION_SCHEMA.TABLES SIT
			where TABLE_NAME like 'Arch_RPT_MGR_OEERT%/OEEDTMTable'
			UNION ALL
			select TABLE_CATALOG,TABLE_NAME CompleteName,SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1) SITTable,
			'COB_MSM_'+SUBSTRING(SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1),0,CHARINDEX('$',SUBSTRING(TABLE_NAME,CHARINDEX('/',TABLE_NAME)+1,LEN(TABLE_NAME)-1))-1) SITType
			from SITMesDb.INFORMATION_SCHEMA.TABLES SIT
			where TABLE_NAME like 'T_MSM_FABENG%/LINEA_TCP%' OR TABLE_NAME like 'T_MSM_FABENG%/LINEA_RENDIMIENTO%'
			

	Open C

	fetch from c into @Catalog,@CompleteName,@SITTable,@SITType

	while @@FETCH_STATUS = 0
	begin
		if @SITType = 'COB_MSM_TIPOS_PARAMETROS'
		begin
			set @SITType = 'COB_MSM_TIPOS_PARAMETRO'
		end
		set @query = 'CREATE SYNONYM [dbo].['+@SITType+'] FOR ['+@Catalog+'].[dbo].['+@CompleteName+']'
		exec(@query)
		print @Catalog+'  '+@SITType
		fetch from c into @Catalog,@CompleteName,@SITTable,@SITType
	end

	close C
	Deallocate C
END try
Begin Catch
	close C
	Deallocate C	
	select ERROR_MESSAGE(),ERROR_LINE()
End Catch
