USE [MES_MSM]
GO

/****** Object:  StoredProcedure [dbo].[MES_GuardarIntervencionMantenimiento]    Script Date: 27/07/2022 10:07:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Daniel Abad Jaraute
-- Create date: 04-05-2022
-- Description:	Se guarda una nueva solicitud de intervención de mantenimiento. Al crearse un nuevo registro en MES, hay que introducir la nueva solicitud en el sistema JDE.
-- =============================================
CREATE PROCEDURE [dbo].[MES_GuardarIntervencionMantenimiento]
	@Linea nvarchar(50),
	@Maquina char(12),
	@EquipoConstructivo char(12),
	@TipoAveria int,
	@DescripcionAveria nvarchar(30),
	@DescripcionProblema nvarchar(80),
	@Usuario varchar(128),
	@NUEVO_CODIGO int out
	--,@ERROR_MSG nvarchar(max) out
AS

DECLARE @ERROR_NUMBER int
DECLARE @ERROR_PROCEDURE nvarchar(max)
DECLARE @ERROR_MESSAGE nvarchar(max)
DECLARE @RESULTADO int = 0
DECLARE @TRANSACTION_OPEN bit = 0
--DECLARE @ID_NEW_ENTRY int = 0

BEGIN
	BEGIN TRY
		SET NOCOUNT ON;
		--SELECT @ERROR_MSG = ''

		-- Obtenemos el siguiente codigo de JDE
		EXEC dbo.MES_ObtenerNuevoCodigoJDE @NUEVO_CODIGO OUTPUT

		IF NOT EXISTS (SELECT 1 FROM Lineas WHERE ID like @Linea) 
			OR NOT EXISTS (SELECT 1 FROM MaquinasEnvasado WHERE CodigoMaquina like @Maquina)
			OR NOT EXISTS (SELECT 1 FROM EquiposConstructivosEnvasado WHERE CodigoEquipo like @EquipoConstructivo)
			OR NOT EXISTS (SELECT 1 FROM TipoAveria WHERE idTipoAveria = @TipoAveria)
			OR NOT EXISTS (SELECT 1 FROM AspNetUsers WHERE Id like @Usuario)
		begin
			SELECT @RESULTADO = 404
			;throw 50404, 'No existe alguna de las referencias', 1
		end

		-- Insertamos la solicitud en el sistema JDE
		
		--Obtenemos el valor NUMB y el valor ASID del maestro de equipos F1201
		DECLARE @NUMB int
		DECLARE @ASID varchar(25)

		SELECT @NUMB = FANUMB, @ASID = FAAPID FROM 
		[JDE].[S4405712].[PRODDTA].[F1201]
		where FAAPID = @EquipoConstructivo

		-- TABLA F4801
		DECLARE @AUX_F4801 TABLE (
			WADOCO	int,
			WADCTO	varchar(2),
			WAPARS	varchar(8),
			WATYPS	char(1),
			WAPRTS	char(1),
			WADL01	varchar(30),
			WASTCM	varchar(30),
			WACO	varchar(5),
			WAMCU	varchar(12),
			WAMMCU	varchar(12),
			WASRST	varchar(2),
			WASUB	varchar(8),
			WAAN8	int,
			WAANO	int, 
			WAANP	int,
			WATRDJ	int,
			WASTRT	int,
			WADRQJ	int,
			WAVR01	varchar(25),
			WANUMB	int,
			WAAPID	varchar(12),
			WATBM	varchar(3),
			WATRT	varchar(3),
			WAUNCD	char(1),
			WAUSER	varchar(10),
			WAPID	varchar(10),
			WAJOBN	varchar(10),
			WAUPMJ	int,
			WATDAY	int,
			WASAID	int,
			WAWR02  varchar(3))

		INSERT INTO @AUX_F4801
		SELECT TOP(1)
			@NUEVO_CODIGO,
			c.TipoOrden_DCTO,
			@NUEVO_CODIGO,
			c.TipoWO_TYPS,
			c.PrioridadWO_PRTS,
			@DescripcionAveria,
			c.ComentarioEstado_STCM,
			c.Empresa_CO,
			c.CentroCoste_MCU,
			c.Sucursal_MMCU,
			c.EstadoInicial_SRST,
			c.Subsidiaria_SUB,
			c.NumeroDireccion_AN8,
			c.UsuarioIniciador_ANO,
			c.UsuarioAsignado_ANP,
			dbo.GregorianoToJuliano(GETDATE()),
			dbo.GregorianoToJuliano(GETDATE()),
			dbo.GregorianoToJuliano(GETDATE()),
			@EquipoConstructivo,
			@NUMB,
			@EquipoConstructivo,
			c.TipoListaMateriales_TBM,
			c.TipoRuta_TRT,
			c.CodigoParalizarWO_UNCD,
			'INTER_MES',
			'INTER_MES',
			'INTER_MES',
			dbo.GregorianoToJuliano(GETDATE()),
			dbo.MES_fn_HoraToJDE(GETDATE()),
			c.NumeroDireccionServicio_SAID,
			convert(varchar(3), (SELECT CodigoJDE from TipoAveria where IdTipoAveria = @TipoAveria))
		FROM MantenimientoConfiguracion c
		
		INSERT INTO MantenimientoJDE_F4801
		--INSERT INTO [JDE].[S4405712].[PRODDTA].[F4801]
		(
			WADOCO,
			WADCTO,
			WAPARS,
			WATYPS,
			WAPRTS,
			WADL01,
			WASTCM,
			WACO,
			WAMCU,
			WAMMCU,
			WASRST,
			WASUB,
			WAAN8,
			WAANO,
			WAANP,
			WATRDJ,
			WASTRT,
			WADRQJ,
			WAVR01,
			WANUMB,
			WAAPID,
			WATBM,
			WATRT,
			WAUNCD,
			WAUSER,
			WAPID,
			WAJOBN,
			WAUPMJ,
			WATDAY,
			WASAID,
			WASFXO,
			WARCTO,
			WARORN,
			WALNID,
			WAPTWO,
			WALOCN,
			WAAISL,
			WABIN,
			WADCG,
			WAANSA,
			WAANPA,
			WADPL,
			WAANT,
			WANAN8,
			WASTRX,
			WADAP,
			WADAT,
			WAPPDT,
			WAWR01,
			WAWR02,
			WAWR03,
			WAWR04,
			WAWR05,
			WAWR06,
			WAWR07,
			WAWR08,
			WAWR09,
			WAWR10,
			WAVR02,
			WAAMTO,
			WASETC,
			WABRT,
			WAPAYT,
			WAAMTC,
			WAHRSO,
			WAHRSC,
			WAAMTA,
			WAHRSA,
			WAITM,
			WAAITM,
			WALITM,
			WAUORG,
			WASOBK,
			WASOCN,
			WASOQS,
			WAQTYT,
			WAUOM,
			WASHNO,
			WAPBTM,
			WASHTY,
			WAPEC,
			WAPPFG,
			WABM,
			WARTG,
			WASPRT,
			WAINDC,
			WARESC,
			WAMOH,
			WATDT,
			WAPOU,
			WAPC,
			WALTLV,
			WALTCM,
			WACTS1,
			WALOTN,
			WALOTP,
			WALOTG,
			WARAT1,
			WARAT2,
			WADCT,
			WASBLI,
			WARKCO,
			WABREV,
			WARREV,
			WADRWC,
			WARTCH,
			WAPNRQ,
			WAREAS,
			WAPHSE,
			WAXDSP,
			WABOMC,
			WAURCD,
			WAURDT,
			WAURAT,
			WAURAB,
			WAURRF,
			WAAAID,
			WANTST,
			WAXRTO,
			WAESDN,
			WAACDN,
			WAMPOS,
			WAAPRT,
			WAAMLC,
			WAAMMC,
			WAAMOT,
			WALBAM,
			WAMTAM
			)
		SELECT 
			WADOCO,
			WADCTO,
			WAPARS,
			WATYPS,
			WAPRTS,
			WADL01,
			WASTCM,
			WACO,
			WAMCU,
			WAMMCU,
			WASRST,
			WASUB,
			WAAN8,
			WAANO,
			WAANP,
			WATRDJ,
			WASTRT,
			WADRQJ,
			WAVR01,
			WANUMB,
			WAAPID,
			WATBM,
			WATRT,
			WAUNCD,
			WAUSER,
			WAPID,
			WAJOBN,
			WAUPMJ,
			WATDAY,
			WASAID,
			WASFXO = '',
			WARCTO = '',
			WARORN = '',
			WALNID = 0.0,
			WAPTWO = 0,
			WALOCN = '',
			WAAISL = '',
			WABIN = '',
			WADCG = 0,
			WAANSA = 0,
			WAANPA = 0,
			WADPL = 0,
			WAANT = 0,
			WANAN8 = 0,
			WASTRX = 0,
			WADAP = 0,
			WADAT = 0,
			WAPPDT = 0,
			WAWR01 = '',
			WAWR02,
			WAWR03 = '',
			WAWR04 = '',
			WAWR05 = '',
			WAWR06 = '',
			WAWR07 = '',
			WAWR08 = '',
			WAWR09 = '',
			WAWR10 = '',
			WAVR02 = '',
			WAAMTO = 0.0,
			WASETC = 0.0,
			WABRT = 0.0,
			WAPAYT = '',
			WAAMTC = 0.0,
			WAHRSO = 0.0,
			WAHRSC = 0.0,
			WAAMTA = 0.0,
			WAHRSA = 0.0,
			WAITM = 0,
			WAAITM = '',
			WALITM = '',
			WAUORG = 0.0,
			WASOBK = 0.0,
			WASOCN = 0.0,
			WASOQS = 0.0,
			WAQTYT = 0.0,
			WAUOM = '',
			WASHNO = '',
			WAPBTM = 0,
			WASHTY = '',
			WAPEC = '',
			WAPPFG = '',
			WABM = '',
			WARTG = '',
			WASPRT = '',
			WAINDC = '',
			WARESC = 0.0,
			WAMOH = 0.0,
			WATDT = 0,
			WAPOU = 0.0,
			WAPC = 0,
			WALTLV = 0,
			WALTCM = 0,
			WACTS1 = 0.0,
			WALOTN = '',
			WALOTP = 0.0,
			WALOTG = '',
			WARAT1 = 0.0,
			WARAT2 = 0.0,
			WADCT = '',
			WASBLI = '',
			WARKCO = '',
			WABREV = '',
			WARREV = '',
			WADRWC = '',
			WARTCH = '',
			WAPNRQ = '',
			WAREAS = '',
			WAPHSE = '',
			WAXDSP = '',
			WABOMC = '',
			WAURCD = '',
			WAURDT = 0,
			WAURAT = 0.0,
			WAURAB = 0,
			WAURRF = '',
			WAAAID = 0,
			WANTST = '',
			WAXRTO = 0,
			WAESDN = 0.0,
			WAACDN = 0.0,
			WAMPOS = 0,
			WAAPRT = '',
			WAAMLC = 0.0,
			WAAMMC = 0.0,
			WAAMOT = 0.0,
			WALBAM = 0.0,
			WAMTAM = 0.0
		FROM @AUX_F4801
		
		-- Tabla F4801T
		DECLARE @AUX_F4801T TABLE(
			WADOCO int,
			WAASID varchar(25),
			WACRCD varchar(3),
			WAISSUE varchar(80),
			WACTR varchar(3),
			WATXA1 varchar(10),
			WAEXR1 varchar(2),
			WATIMEZONES varchar(2),
			WACRDC varchar(3),
			WACRRM char(1),
			WACRTU varchar(10)
		)
		
		INSERT INTO @AUX_F4801T
		SELECT TOP(1)
			@NUEVO_CODIGO,
			@ASID,
			c.CodigoDivisaDesde_CRCD,
			@DescripcionProblema,
			c.Pais_CTR,
			c.Tasas_TXA1,
			c.TasasCodigoExp1_EXR1,
			c.TimeZone_TIMEZONES,
			c.CodigoDivisaPara_CRDC,
			c.ModoDivisa_CRRM,
			'INTER_MES'
		FROM MantenimientoConfiguracion c

		INSERT INTO MantenimientoJDE_F4801T
		--INSERT INTO [JDE].[S4405712].[PRODDTA].[F4801T]
		(
			WADOCO,
			WAASID,
			WACRCD,
			WAISSUE,
			WACTR,
			WATXA1,
			WAEXR1,
			WATIMEZONES,
			WACRDC,
			WACRRM,
			WACRTU,
			WALINE,
			WAMWDH,
			WASCSP,
			WASHFT,
			WASRCN,
			WALEDG,
			WACTS4,
			WACTS7,
			WACTS8,
			WAAID,
			WAALSE,
			WAATST,
			WABSEQ,
			WACHPR,
			WACRCE,
			WACRCF,
			WAD5J,
			WAD6J,
			WADRAW,
			WADUAL,
			WAMPCE,
			WAMPRC,
			WAOBJ,
			WAOTAM,
			WAPRJM,
			WAPRRP,
			WASHPP,
			WASQOR,
			WASRKF,
			WASRNK,
			WASSOQ,
			WATRAF,
			WAUOM2,
			WAWR11,
			WAWR12,
			WAWR13,
			WAWR14,
			WAWR15,
			WAWR16,
			WAWR17,
			WAWR18,
			WAWR19,
			WAWR20,
			WAJBCD,
			WAVFWO,
			WAPMTN,
			WAPRODM,
			WAWHO2,
			WAAR1,
			WAPHN1,
			WATMCO,
			WAMTHPR,
			WAENTCK,
			WARYIN,
			WARSTM,
			WAREGION,
			WALNGP,
			WAGLCCV,
			WAGLCNC,
			WACOVGR,
			WAASN4,
			WAASN2,
			WASEST,
			WASEET,
			WADSAVNAME,
			WAPRODF,
			WACSLPRT,
			WAMCUCSL,
			WARLOT,
			WAFAILCD,
			WAFAILDT,
			WAFAILTM,
			WAREPDT,
			WAREPTM,
			WAVEND,
			WAAN8AS,
			WAAN8SRM,
			WASRYN,
			WAENTCKS,
			WACURBALM1,
			WACURBALM2,
			WACURBALM3,
			WACRR,
			WAVMRS31,
			WAVMRS32,
			WASEQN,
			WAPLMR,
			WAPLLB,
			WAPLOS,
			WABGTC,
			WATOEM,
			WATOPL,
			WAPLSA,
			WAPLSU,
			WAESSA,
			WAESSU,
			WAACSA,
			WAACSU,
			WAOACM,
			WARACM,
			WAHPLF,
			WAVMRS33,
			WASCALL,
			WAISNO,
			WARMTHD,
			WADOC,
			WADCT,
			WAKCO,
			WACOCH,
			WALNID,
			WAXEVT,
			WAMCULT,
			WAWSCHF,
			WADFMDP,
			WAPMPN,
			WAPNS
			)
		SELECT 
			WADOCO,
			WAASID,
			WACRCD,
			WAISSUE,
			WACTR,
			WATXA1,
			WAEXR1,
			WATIMEZONES,
			WACRDC,
			WACRRM,
			WACRTU,
			WALINE = '',
			WAMWDH = '',
			WASCSP = 0,
			WASHFT = '',
			WASRCN = '',
			WALEDG = '',
			WACTS4 = 0.0,
			WACTS7 = 0.0,
			WACTS8 = 0.0,
			WAAID = '',
			WAALSE = '',
			WAATST = 0,
			WABSEQ = 0,
			WACHPR = '',
			WACRCE = '',
			WACRCF = '',
			WAD5J = 0,
			WAD6J = 0,
			WADRAW = '',
			WADUAL = '',
			WAMPCE = '',
			WAMPRC = '',
			WAOBJ = '',
			WAOTAM = 0.0,
			WAPRJM = 0,
			WAPRRP = '',
			WASHPP = '',
			WASQOR = 0.0,
			WASRKF = '',
			WASRNK = 0.0,
			WASSOQ = 0.0,
			WATRAF = '',
			WAUOM2 = '',
			WAWR11 = '',
			WAWR12 = '',
			WAWR13 = '',
			WAWR14 = '',
			WAWR15 = '',
			WAWR16 = '',
			WAWR17 = '',
			WAWR18 = '',
			WAWR19 = '',
			WAWR20 = '',
			WAJBCD = '',
			WAVFWO = '',
			WAPMTN = '',
			WAPRODM = '',
			WAWHO2 = '',
			WAAR1 = '',
			WAPHN1 = '',
			WATMCO = 0,
			WAMTHPR = '',
			WAENTCK = '',
			WARYIN = '',
			WARSTM = 0,
			WAREGION = '',
			WALNGP = '',
			WAGLCCV = '',
			WAGLCNC = '',
			WACOVGR = '',
			WAASN4 = '',
			WAASN2 = '',
			WASEST = 0,
			WASEET = 0,
			WADSAVNAME = '',
			WAPRODF = '',
			WACSLPRT = 0,
			WAMCUCSL = '',
			WARLOT = '',
			WAFAILCD = '',
			WAFAILDT = 0,
			WAFAILTM = 0,
			WAREPDT = 0,
			WAREPTM = 0,
			WAVEND = 0,
			WAAN8AS = 0,
			WAAN8SRM = 0,
			WASRYN = '',
			WAENTCKS = '',
			WACURBALM1 = 0,
			WACURBALM2 = 0,
			WACURBALM3 = 0,
			WACRR = 0,
			WAVMRS31 = '',
			WAVMRS32 = '',
			WASEQN = 0,
			WAPLMR = 0.0,
			WAPLLB = 0.0,
			WAPLOS = 0.0,
			WABGTC = 0.0,
			WATOEM = 0.0,
			WATOPL = 0.0,
			WAPLSA = 0.0,
			WAPLSU = 0.0,
			WAESSA = 0.0,
			WAESSU = 0.0,
			WAACSA = 0.0,
			WAACSU = 0.0,
			WAOACM = 0.0,
			WARACM = 0.0,
			WAHPLF = '',
			WAVMRS33 = '',
			WASCALL = '',
			WAISNO = 0,
			WARMTHD = '',
			WADOC = 0,
			WADCT = '',
			WAKCO = '',
			WACOCH = '',
			WALNID = 0.0,
			WAXEVT = '',
			WAMCULT = '',
			WAWSCHF = '',
			WADFMDP = '',
			WAPMPN = '',
			WAPNS = 0
		FROM @AUX_F4801T
		
		-- Tabla F1307
		DECLARE @AUX_F1307 TABLE (
			F1NUMR int,
			F1TREC char(1),
			F1EFTB int,
			F1BEGT int,
			F1EWST varchar(2),
			F1DOCO int,
			F1RMK varchar(30),
			F1USER varchar(10),
			F1PID varchar(10),
			F1JOBN varchar(10),
			F1UPMJ int,
			F1UPMT int
		)

		INSERT INTO @AUX_F1307
		SELECT TOP(1)
			@NUMB,
			c.TipoRegistro_TREC,
			dbo.GregorianoToJuliano(GETDATE()),
			dbo.MES_fn_HoraToJDE(GETDATE()),
			c.EstadoInicial_SRST,
			@NUEVO_CODIGO,
			'INTERFASE_MES',
			'INTER_MES',
			'INTER_MES',
			'INTER_MES',
			dbo.GregorianoToJuliano(GETDATE()),
			dbo.MES_fn_HoraToJDE(GETDATE())
		FROM MantenimientoConfiguracion c

		INSERT INTO MantenimientoJDE_F1307
		--INSERT INTO [JDE].[S4405712].[PRODDTA].[F1307]
		(
			F1NUMR,
			F1TREC,
			F1EFTB,
			F1BEGT,
			F1EWST,
			F1DOCO,
			F1RMK,
			F1USER,
			F1PID,
			F1JOBN,
			F1UPMJ,
			F1UPMT,
			F1EFTE,
			F1ENDT,
			F1STHR,
			F1CUMH,
			F1LFR,
			F1LHR,
			F1LMR,
			F1LM4R,
			F1LM5R,
			F1LM6R
			)
		SELECT 
			F1NUMR,
			F1TREC,
			F1EFTB,
			F1BEGT,
			F1EWST,
			F1DOCO,
			F1RMK,
			F1USER,
			F1PID,
			F1JOBN,
			F1UPMJ,
			F1UPMT,
			F1EFTE = 0,
			F1ENDT = 0,
			F1STHR = 0.0,
			F1CUMH = 0.0,
			F1LFR = 0.0,
			F1LHR = 0.0,
			F1LMR = 0.0,
			F1LM4R = 0.0,
			F1LM5R = 0.0,
			F1LM6R = 0.0
		FROM @AUX_F1307

		-- Insertamos la solicitud en MES
		BEGIN TRAN
		SELECT @TRANSACTION_OPEN = 1

		INSERT INTO dbo.MantenimientoIntervenciones (OT, Estado, Linea, Maquina, EquipoConstructivo, IdTipoAveria, DescripcionAveria, DescripcionProblema, FechaCreacion, Usuario)
		VALUES(@NUEVO_CODIGO, (SELECT c.EstadoInicial_SRST FROM MantenimientoConfiguracion c), @Linea, @Maquina, @EquipoConstructivo, @TipoAveria, @DescripcionAveria, @DescripcionProblema, GETUTCDATE(), @Usuario)

		if (@RESULTADO = 0)
		BEGIN 
			commit
		END ELSE
		BEGIN 
			rollback
		END

		SELECT @TRANSACTION_OPEN = 0

		RETURN @RESULTADO

	END TRY
	BEGIN CATCH
		IF @TRANSACTION_OPEN = 1
		BEGIN
			rollback
		END

		IF @RESULTADO = 0
		BEGIN
			SELECT @RESULTADO = 10008
		END

		SET @ERROR_NUMBER = ERROR_NUMBER()
		SET @ERROR_PROCEDURE = ERROR_PROCEDURE()
		SELECT @ERROR_MESSAGE = isnull(@ERROR_MESSAGE, '') +' '+ ERROR_MESSAGE()
		--SELECT @ERROR_MSG = @ERROR_MESSAGE
		IF @ERROR_NUMBER = 547 -- Se referencia desde otras tablas
		SET @RESULTADO = 10002
		ELSE IF (@ERROR_NUMBER = 2627 ) -- Clave primaria duplicada
		SET @RESULTADO = 10001

		SELECT CODE = @RESULTADO, ERROR = @ERROR_MESSAGE
		RETURN @RESULTADO

	END CATCH
END

GO


